### ISSUE TITLE
更新之後資料夾名稱出亂碼

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#10]
更新到2016.4.22.3之後抓下來的資料夾名稱，本來如果是第162話，更新以後抓下來的163 164變成
��163��
��164��
我的系統是在日文語系下不知道有沒有關係
不過更新前用的應該是2016.4.20的時候是正常的。

**Comment by eight04** [comment]
有網址嗎？我稍微看了下，可能是編碼錯了

**Comment by eight04** [comment]
嘗試升級到 2016.4.22.3 看有沒有解決

**Comment by kesdoputr** [comment]
更新到2016.4.26.1已無此問題，感謝更新。

**Comment by eight04** [comment]
Fixed in 2016.4.26.1
