### ISSUE TITLE
希望能支援騰訊動漫

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#102]
有些漫畫似乎是這邊獨家，不太會被轉到其他漫畫網站的樣子
不知道有沒有機會解析他?

http://ac.qq.com/Comic/

**Comment by IthildinX** [comment]
最近看這兩部似乎都沒找到其他漫畫站有複製

http://ac.qq.com/Comic/comicInfo/id/626619
http://ac.qq.com/Comic/comicInfo/id/537737 <= 這個還掛了簽約跟獨家的tag 

另外問一下comico這種條漫有可能抓嗎?
不知道他的圖檔會不會是一長條 抓下來閱讀效果也不好.....

**Comment by eight04** [comment]
> http://ac.qq.com/Comic/comicInfo/id/626619
> http://ac.qq.com/Comic/comicInfo/id/537737

已確認

關於長條漫畫，我有遇過那種抓下來是一張張從中間截斷的，要把圖片接起來才能讀。那時還特地寫了一個程式用來連續開圖，可以參考︰
https://github.com/eight04/comic-viewer

**Comment by eight04** [comment]
於 2018.3.9 加入
