### ISSUE TITLE
關於騰訊漫畫的章節命名問題-無數字編號

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#104]
抱歉再次打擾了，由於騰訊漫畫有些作品的章節命名沒有第1話、第2話這種數字編號，
所以抓下來的資料夾排序會搞不懂順序，
請問能類似 Issue99那樣修改檔名的設定，在章節資料夾的部分不單純使用原始名稱，在前面加上第X話這樣子嗎?

舉例連結:
http://ac.qq.com/Comic/comicInfo/id/630358
http://ac.qq.com/Comic/comicInfo/id/629088

**Comment by eight04** [comment]
你提供的連結也沒有標明話數，Comic Crawler 怎麼知道是幾話？

若只要求順序，或許可以在檔名加上 URL 最後的數字。例︰
```
http://ac.qq.com/ComicView/index/id/629088/cid/2
-> 2 - 预告+0.5话
http://ac.qq.com/ComicView/index/id/629088/cid/4
-> 4 - 逼婚！？拆了你的CP哼！
```
雖然可以保持順序，但仍然無法從該數字看出來是第幾話。

另外一個解法是調整資料夾的排序設定，用建立日期排序。

> 類似 Issue99那樣

我看不出來這和 #99 有什麼關係。

**Comment by IthildinX** [comment]
他的編號就是話數的順序，所以拿那個數字排應該就沒問題

我以為99也是除了原始檔名之外還加了排序數字在前面的設定？
只是用在圖檔檔名上

**Comment by eight04** [comment]
artstation 那是相簿的 ID，Comic Crawler 並沒有對集數排序。

https://github.com/eight04/ComicCrawler/blob/d9eac278c42f3caf26225bc61b99b112e3264b08/comiccrawler/mods/artstation.py#L36

**Comment by IthildinX** [comment]
啊 補述一下 我是指類似99提到的appendoriginalfilename選項這樣
前面有個數字，後面是原本的標題名稱，那個數字抓URL最後的編號看起來就是閱讀順序了，挺好的？

**Comment by eight04** [comment]
於 2018.3.15 修正。
