### ISSUE TITLE
希望支援友繪漫畫or受漫畫

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#110]
有獨家漫畫，例如:

邪气凛然
http://www.wuyouhui.net/lianai/xieqilinran/
http://www.xznj120.com/lianai/591/
雖然根據第一話顯示漫畫島獨家，但漫畫島類似布卡漫畫，較新的章節會要求專屬APP，可能無法從電腦直接下載

很纯很暧昧
http://www.wuyouhui.net/rexue/henchunhenzuomei/
http://www.xznj120.com/rexue/1290/
此漫畫在騰訊要求收費，在漫畫島要求專屬APP，因此可能還是需要這兩個網站之一

補充一個
http://www.wuyouhui.net/zongcai/rugunuanhunmanhua/
http://www.xznj120.com/rexue/2824/
入骨暖婚也是藤訊開始收費，在這兩個網頁可以看到後續

**Comment by eight04** [comment]
這兩個站看起來非常像，但提供的圖片檔來源並不一樣呢（我覺得受漫畫的比較清楚？）︰
http://www.xznj120.com/lianai/591/7743.html
http://www.wuyouhui.net/lianai/xieqilinran/42768.html

但也有圖片完全相同的︰
http://www.xznj120.com/lianai/591/142672.html
http://www.wuyouhui.net/lianai/xieqilinran/208852.html
![image](https://user-images.githubusercontent.com/1324510/39638653-7edfc382-4ff9-11e8-8d53-a5c7d6d04310.png)

在你的使用經驗裡這兩站有什麼差別嗎？

**Comment by eight04** [comment]
測試時發現 72 話不能看
http://www.xznj120.com/lianai/591/70521.html
