### ISSUE TITLE
Tumblr下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#117]
更新至最新版comiccrawler後無法下載:
https://drive.google.com/file/d/1qovQouv_fbvs4YEShUUIa8uGL8z3nLki/view

設定檔裡面新增的設定值:
https://drive.google.com/file/d/1nls1sWQkAHYPtgtolcRpqKraHGZ7ChKU/view
user_agent 那一欄請問要填什麼?
我在瀏覽器中tumblr的cookie列表裡找不到這一項

**Comment by eight04** [comment]
User-Agent 是用來識別瀏覽器種類的 HTTP Header。比較簡易的取得方法是使用 Web Console（支援 Chrome & Firefox）︰

1. 按 F12，開啟 Console
2. 輸入指令︰`copy(navigator.userAgent)`，按下 Enter。
3. 成功複製 User-Agent 至剪貼簿。

需要 User-Agent 的原因︰

> tumblr 在登入後會記錄所使用的瀏覽器資訊（User-Agent），若使用不同的瀏覽器，即使用相同的 Cookie 也無法登入。換句話說，為要登入 Tumblr，Comic Crawler 除了要使用相同的 Cookie，還需要偽裝成你登入時所使用的瀏覽器（使用和瀏覽器相同的 User-Agent）。

**Comment by chenhan200** [comment]
https://drive.google.com/file/d/1NNaLe-dxQURe9c1MRUHtYnk792_CeghM/view
將複製到的東西直接貼上還是不能下載
請問是哪邊做錯了呢?

**Comment by eight04** [comment]
錯誤訊息和網址是？

**Comment by eight04** [comment]
Fixed in 2018.5.13.

> 順帶一提 設定檔裡新增的設定值是我自己手動改的
> 不知道這樣會不會有問題?

不清楚這是什麼意思。Comic Crawler 的設定都是要手動改的，它不會自動地跟你要登入資料，若發生錯誤也只會告訴你無法登入而已。

**Comment by chenhan200** [comment]
抱歉說的不夠清楚
我是指 'cookie_pfx =' 和 'cookie_pfx ='
這兩行新設定在更新版本後沒有自動加進去
於是我自己手動加了

**Comment by eight04** [comment]
如果在更新後，開啟了 Comic Crawler，馬上打開設定檔，那麼看不到新設定是很正常的。別忘了 Comic Crawler 只在 **關閉前** 才會把資料寫回硬碟。

除此之外的狀況我就想不到了。沒有什麼因素可以造成設定消失。
