### ISSUE TITLE
Tab in image title causes download to fail

### ISSUE THREAD

**Issue by Kilo19** [eight04/ComicCrawler#119]
https://github.com/eight04/ComicCrawler/blob/c259e5f193d5b1c3e1401407a8023bfbf3c7d736/comiccrawler/core/__init__.py#L145-L157

This table is not complete. When downloading from http://seiga.nicovideo.jp/seiga/im6309021, the image title contains tab (\t) in the middle, causing an illegal path error on Windows. I added a pair that maps "\t" to " " on my machine and it fixed the issue. I don't feel like opening a pull request for such a simple line, so feel free to incorporate it in the next release.

**Comment by eight04** [comment]
Maybe we should replace any whitespace sequence with a single space " ":
```py
s = re.sub(r"\s+", " ", s)
```

**Comment by eight04** [comment]
Fixed in 2018.6.8. Please backup your profile before the upgrade.

**Comment by eight04** [comment]
See #125
