### ISSUE TITLE
不知道哪個是執行檔

### ISSUE THREAD

**Issue by s4028600** [eight04/ComicCrawler#12]
下載下來只有這幾個檔案
ComicCrawler
.gitignore
cute.py
README.rst
requirements.txt
setup.py
comiccrawler

每個檔案執行後都一下子就不見了
pip install comiccrawler的指令也執行過了
求救

**Comment by eight04** [comment]
你下載到的東西叫作「原始碼」，是給開發者用的。

如果你是一般使用者，按照 [下載和安裝](https://github.com/eight04/ComicCrawler#%E4%B8%8B%E8%BC%89%E5%92%8C%E5%AE%89%E8%A3%9Dwindows) 這裡說明的步驟，把 Python、Node.js、Comic Crawler 都安裝好後，在 cmd 中輸入「comiccrawler gui」指令，就會出現主視窗了。

我等等把使用說明寫詳細點。

**Comment by s4028600** [comment]
那我要去哪裡下載ComicCrawler啊?
找不到其他載點......

**Comment by eight04** [comment]
Comic Crawler 不需要手動下載。

[下載並安裝完 Python 後](https://github.com/eight04/ComicCrawler#install-python)，你會得到一個 `pip` 指令。接下來只要在 cmd 內輸入 `pip install comiccrawler` 就可以了。

**Comment by s4028600** [comment]
???
那要怎麼開下載視窗?
![default](https://cloud.githubusercontent.com/assets/19856067/15985414/31f12906-3027-11e6-8b94-c356b47f842c.png)
這是執行pip install comiccrawler的樣子

**Comment by eight04** [comment]
在 cmd 中輸入「comiccrawler gui」指令，就會出現主視窗了

**Comment by s4028600** [comment]
喔喔
可以了
感謝

順便問個問題
http://www.chuixue.com/manhua/4344/
無法解析的樣子
會跑出

吹雪
解析錯誤！
'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
> http://www.chuixue.com/manhua/4344/
> 無法解析

已確認

> 無法改下載目錄

下載目錄可以在 [設定檔](https://github.com/eight04/ComicCrawler#%E8%A8%AD%E5%AE%9A%E6%AA%94) 中更改

**Comment by eight04** [comment]
已於 2016.6.12 修正
