### ISSUE TITLE
Pixiv任務名稱全形空格問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#125]
更新至2018.6.8版後
檢查圖書館更新時，Pixiv的任務名稱裡如果有全形空格
會另外生成新任務和新資料夾，舊的任務和資料夾則會被忽視不管
https://drive.google.com/open?id=1K-Qr4IOdeeVGP4mRjclKmCTi4EpbQtki

**Comment by eight04** [comment]
https://github.com/eight04/ComicCrawler/commit/28183b1142d3f459376fa279725eddf7ed8b29a8 會影響手動修改的標題（手動把任務改名，加入兩個空格，實際上下載時只剩一個），我決定 revert https://github.com/eight04/ComicCrawler/commit/28183b1142d3f459376fa279725eddf7ed8b29a8。
