### ISSUE TITLE
Feature request: 漫畫最後更新時間

### ISSUE THREAD

**Issue by DummySYSTEM** [eight04/ComicCrawler#128]
記錄最後一次該漫畫更新的日期/時間, 方便找出很久沒再更新的

**Comment by eight04** [comment]
進入下載目的地資料夾，以修改時間倒序排列就可以了？

**Comment by DummySYSTEM** [comment]
1. 資料夾可能已不存在 (例如看完刪了)
2. 就算有資料夾也比不上直接在Comic Crawler UI 的漫畫列表一次過看到方便

**Comment by eight04** [comment]
於 2018.6.21 連同排序功能加入。另外提醒，由於在這之前的任務都沒有記錄更新時間，所以會看到很多「無」。
