### ISSUE TITLE
HiDPI支持

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#13]
如题
图形界面在我的surface pro3上看起来非常小。。

**Comment by eight04** [comment]
它用的是預設字型，但是我不太確定 tkinter 是如何決定預設字型大小的。

是只有 Comic Crawler 的字型特別小嗎？有截圖嗎？

**Comment by petronny** [comment]
![2016-06-29 12-02-49](https://cloud.githubusercontent.com/assets/5357170/16440118/7e47ff0a-3df1-11e6-98ea-df45d1c08b35.png)

**Comment by eight04** [comment]
我找了一些相關的討論，不過我沒有機器可以測試。你可以試看看 [這段程式碼](http://stackoverflow.com/a/26539115) 是否能正確的偵測出目前的 DPI 嗎？

**Comment by petronny** [comment]
```
import tkinter as tk
root = tk.Tk()

width_px = root.winfo_screenwidth()
height_px = root.winfo_screenheight() 
width_mm = root.winfo_screenmmwidth()
height_mm = root.winfo_screenmmheight() 
# 2.54 cm = in
width_in = width_mm / 25.4
height_in = height_mm / 25.4
width_dpi = width_px/width_in
height_dpi = height_px/height_in 

print('Width: %i px, Height: %i px' % (width_px, height_px))
print('Width: %i mm, Height: %i mm' % (width_mm, height_mm))
print('Width: %f in, Height: %f in' % (width_in, height_in))
print('Width: %f dpi, Height: %f dpi' % (width_dpi, height_dpi))
```
此时得到
```
Width: 2160 px, Height: 1440 px
Width: 571 mm, Height: 381 mm
Width: 22.480315 in, Height: 15.000000 in
Width: 96.084063 dpi, Height: 96.000000 dpi
```

不过SurfacePro3没571 mm x 381 mm 那么大。。

```
import ctypes
user32 = ctypes.windll.user32
user32.SetProcessDPIAware()
[w, h] = [user32.GetSystemMetrics(0), user32.GetSystemMetrics(1)]
print('Size is %f %f' % (w, h))
```
这些linux下跑不了了，不过参考原文推测w和h应该为2160和1440
```
curr_dpi = w*96/width_px
print('Current DPI is %f' % (curr_dpi))   
```
所以推测结果应该还是96吧。。并没有什么用

不过我觉得可以参考Gnome的解决方案。Gnome3通过
```
gsettings set org.gnome.desktop.interface scaling-factor 2
```
来处理HiDPI, 我们是不是也可以在配置文件中加一个interface scaling factor呢？
不用考虑小数，Gnome3上面这个就是只能设置整数

**Comment by eight04** [comment]
這樣看起來，應該可以利用 `gsettings get org.gnome.desktop.interface scaling-factor` 去抓放大比例，而不去偵測 DPI？我等等來實作

**Comment by eight04** [comment]
試試 https://github.com/eight04/ComicCrawler/tree/dev-dpi

**Comment by petronny** [comment]
现在整个窗口区域已经放大一倍了！
不过字体和各种widget还是一倍的，另外下面这个标签页的白色部分宽度不对
![2016-06-30 00-36-49](https://cloud.githubusercontent.com/assets/5357170/16460603/c31e17d6-3e5a-11e6-952f-f4549b71919a.png)

**Comment by eight04** [comment]
我要看到 [相關討論](http://stackoverflow.com/questions/34132203/scaling-of-tkinter-python-tk-gui-in-4k-38402160-resolution) 表示在 linux 底下沒用，但在我的 Windows 7 底下是有用的︰
![](http://i.imgur.com/7Uwv3m6.png)

總之，我先試著把內建字型從 px 轉成 pt 看看有沒有效。
https://github.com/eight04/ComicCrawler/commit/a61b73063f53dbb13c272388f543af24e0c0f569

**Comment by petronny** [comment]
a61b730 在我这里是有用的！不过貌似这里的行高还有些问题
![2016-06-30 22-02-36](https://cloud.githubusercontent.com/assets/5357170/16490976/779b59d6-3f0e-11e6-9a8c-acca1cb64426.png)

**Comment by eight04** [comment]
https://github.com/eight04/ComicCrawler/commit/bbd6887b917a8d9e58bbf142d047b8726540e9bf
不知道如何取得 rowheight，直接拿 20 來乘

**Comment by petronny** [comment]
20我这看起来稍微有点大
用289行得到的size怎么样
比如2*size*scale?

**Comment by eight04** [comment]
20 是我直接量上面那張圖藍色選取區的高度。我的也是 20px

**Comment by petronny** [comment]
确实如此哈。。

**Comment by eight04** [comment]
已於 2016.6.30 修正！感謝回報

**Comment by eight04** [comment]
呃，我發現這個沒修到。不過影響不大，就不對它做單獨的 release 了？
https://github.com/eight04/ComicCrawler/commit/8616e3469da74bb1ac193e544a9a2f6e9f57df54#commitcomment-18064120
