### ISSUE TITLE
多线程支持

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#14]
如题。可以大幅度加快下载速度。
建议在配置文件增加一项来设置线程数

**Comment by eight04** [comment]
我認為使用多線下載對漫畫網站有負面影響，所以沒有做這個功能。

順帶一提，Comic Crawler 原先是為了取代停止維護的 JComicDownloader 而開發的，其中 JComicDownloader 的作者[也有提到這件事](https://sites.google.com/site/jcomicdownloader/questions-and-answers#q20)

**Comment by petronny** [comment]
确是如此。。

不过对于访问过慢的站点我还是希望有个2线程的。
加个提示让大家注意一下一般情况不应开多线程，但是还是有选项？

当然没有也无所谓啦。。

**Comment by eight04** [comment]
那就維持原本的決定囉
