### ISSUE TITLE
請求添加: 動漫易

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#146]
是否可以支援 "動漫易" 這個網站？

https://www.twocomic.com/

像是怪怪守護神這部就有持續再更新
https://www.twocomic.com/html/6698.html

謝謝。

**Comment by eight04** [comment]
它的圖片是從 8comic 抓的︰
https://comicbus.com/html/6698.html

我等等把 8comic 修一修。

**Comment by eight04** [comment]
於 2018.9.7 修正 comicbus 域名問題。
