### ISSUE TITLE
請求添加: 古风漫画网

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#147]
首頁:
http://www.gufengmh.com/
有些騰訊開始收費的漫畫在這邊找的到
各自在其他未支援的漫畫網站能找到一些，但古風最完整

绝世炼丹师
http://www.gufengmh.com/manhua/jueshiliandanshi/

我家殿下要挂了
http://www.gufengmh.com/manhua/wojiadianxiayaoguale/

重生之都市修仙 
http://www.gufengmh.com/manhua/zhongshengzhidushixiuxian/

我在末世有套房 
http://www.gufengmh.com/manhua/wozaimoshiyoutaofang/

史上第一掌门 
http://www.gufengmh.com/manhua/shishangdiyizhangmen/

**Comment by eight04** [comment]
於 2018.9.11 加入。
