### ISSUE TITLE
Sleep between download each image

### ISSUE THREAD

**Issue by DummySYSTEM** [eight04/ComicCrawler#152]
is there no implement of sleep between download each image? I see sleep in analysis only

p.s. just recover, sorry for missing a while.

**Comment by eight04** [comment]
You can add a delay between each image by defining a `rest` constant. See [Module example](https://github.com/eight04/ComicCrawler#module-example):
```py
# Wait 5 seconds before downloading another image. Optional, default to 0.
rest = 5
```
