### ISSUE TITLE
Pixiv下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#154]
更新到2018.9.23版後變得沒辦法以tag做分類下載

以以下網址為例:
https://www.pixiv.net/member_illust.php?id=20146&tag=%E6%9D%B1%E6%96%B9
將上列網址加入任務，不會只下載該作者有這個tag的圖片，而是會全部下載
也就是變成跟加入 https://www.pixiv.net/member_illust.php?id=20146 這段網址是一樣的
以前加入過的任務也全部受到影響，檢查更新後會連沒有該tag的圖片也一起下載
希望能改回原本可以用tag做分類下載的功能
謝謝

**Comment by eight04** [comment]
在改版前分析這類 tag 頁面會得到怎樣的任務標題？

**Comment by chenhan200** [comment]
得到的任務名稱都是一樣的
以我貼的網址為例，會是 20146 - スギ

**Comment by eight04** [comment]
那怎麼知道該任務有沒有附加 tag？

**Comment by eight04** [comment]
我想把 tag 加入標題，類似 `20146 - スギ (東方)`

**Comment by eight04** [comment]
於 2018.9.24 修正。
