### ISSUE TITLE
Duplicated episode title in ikanman

### ISSUE THREAD

**Issue by eight04** [eight04/ComicCrawler#156]
https://tw.manhuagui.com/comic/3038/

**Comment by eight04** [comment]
Fixed in 2018.9.30.

**Comment by IthildinX** [comment]
https://tw.manhuagui.com/comic/25799/
異世界精靈的日常喜劇的最新一話(目前是第70話)會被誤判為番外篇 而不是單話

之前第69為最新一話的時候抓下來也是前面掛著番外篇而不是單話

**Comment by eight04** [comment]
於 2018.10.24 修正
