### ISSUE TITLE
"开启资料夹"功能的跨平台实现

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#16]
`gui.py`中564行

```
os.startfile(folder)
```

在OSX下可以使用

```
os.system('open "%s"' % folder)
```

Linux下可以使用

```
os.system('xdg-open "%s"' % folder)
```

**Comment by eight04** [comment]
:+1:

[這篇](http://stackoverflow.com/questions/17317219/is-there-an-platform-independent-equivalent-of-os-startfile) 有人提到可以用 webbrowser.open，不過也有人說在 mac 底下沒有用。

pypi 上有個 [desktop](https://pypi.python.org/pypi/desktop) package，但我在 python3 + windows 7 會 import error。

**Comment by eight04** [comment]
在 2016.7.1 做了暫時的修正。

我寄了一封信給 desktop 的作者，如果有後續的話可能就改成用 desktop
