### ISSUE TITLE
受漫畫網域更換

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#163]
受漫畫首頁由http://www.33am.cn/ 變為 http://www.36rm.cn/
修改xznj120.py檔案中的domain列表增加支援後可修正

圖書館已存漫畫可以用#79的程式碼修正成新網址，
但原先解析出http://www.33am.cn/ 的漫畫章節在下載時會出錯，
需要手動將pool中檔案刪除欲下載的章節，再重新解析出http://www.36rm.cn/ 網域的連結，
就可以正常下載

**Comment by starobots** [comment]
是，我用#79的脚本也会出现pool档案和新的修改的对不上的问题。
