### ISSUE TITLE
希望能增加汗汗漫画的境像

### ISSUE THREAD

**Issue by qewrwerwer** [eight04/ComicCrawler#169]
希望增加http://www.hhcool.com/和http://www.hhimm.com/作为汗汗漫画的备份
因为现在那个常变化 有3个域名已经挂了

**Comment by qewrwerwer** [comment]
http://comic.kukudm.com/ 和https://www.177mh.net/也应该加上， ck101已经消失 暗暗漫画已不能访问

**Comment by eight04** [comment]
你給的網址不是汗汗漫畫。不過我檢查了 www.hhmmoo.com ，的確有新網域 www.hheess.com 。

另外，請為不同的 bug 開各自的 issue。
