### ISSUE TITLE
右键菜单失去焦点后不会消失

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#17]
如题
![2016-07-01-020705_1147x605_scrot](https://cloud.githubusercontent.com/assets/5357170/16498902/8dc4f240-3f30-11e6-8d7e-1ee5706616ea.png)
除非点了上面的什么否则永远不会消失。。。

**Comment by eight04** [comment]
看起來是 linux 獨有的問題
http://stackoverflow.com/questions/21200516/python3-tkinter-popup-menu-not-closing-automatically-when-clicking-elsewhere
這裡有寫簡單的 workaround，測試看看有沒有效？
https://mail.python.org/pipermail/python-list/2002-September/161459.html

**Comment by petronny** [comment]
第二个链接的代码，右键菜单在窗口内失去焦点时不会消失。但是在整个窗口失去焦点时会消失了。
参考第一个链接，把post改为tk_popup之后，即
```
from tkinter import *

root = Tk()

def hello():
        print("hello!")

def popup(event):
        menu.tk_popup(event.x_root, event.y_root)
        menu.focus_set()

def popupFocusOut(self,event=None):
        menu.unpost()

# create a canvas
frame = Frame(root, width=512, height=512)
frame.pack()

# create a popup menu
menu = Menu(frame, tearoff=0)
menu.add_command(label="Undo", command=hello)
menu.add_command(label="Redo", command=hello)
menu.bind("<FocusOut>",popupFocusOut)

# attach popup to canvas
frame.bind("<Button-3>", popup)

mainloop()
```
窗口内失去焦点内也会正常消失了

不过那个unpost函数应该怎么处理呢？可以删掉吗，如果删掉的话，窗口内失去焦点内也会正常消失，功能上没有区别。

**Comment by eight04** [comment]
menu.focus_set()
	
這行是必要的嗎？

**Comment by petronny** [comment]
去掉的话整个demo中看不到什么异样。。

**Comment by eight04** [comment]
已於 2016.7.2 修正
