### ISSUE TITLE
 http://www.mh160.com失效了

### ISSUE THREAD

**Issue by syaofox** [eight04/ComicCrawler#171]
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.mh160.com', port=443): Max retries exceeded with url: /kanmanhua/17217/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')))

**Comment by eight04** [comment]
我現在點進去被轉到 https://www.laimanhua.com/
