### ISSUE TITLE
DM5失效                   

### ISSUE THREAD

**Issue by kof11** [eight04/ComicCrawler#173]
http://www.dm5.com/manhua-yizhongzufengsuniangpingjianzhinan/
DM5失效

**Comment by eight04** [comment]
我測試沒有問題，請安裝最新版後附上錯誤訊息。

**Comment by kof11** [comment]
> 
> 
> 我測試沒有問題，請安裝最新版後附上錯誤訊息。

https://thumbsnap.com/uh4zxvr5?src=tsd
我重新安裝後還是一樣

**Comment by eight04** [comment]
你沒有安裝 Node.js

**Comment by kof11** [comment]
> 
> 
> 你沒有安裝 Node.js

原來是這個東西，多謝，成功了
