### ISSUE TITLE
有关tk的主题

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#18]
如你所见tk的默认主题在linux下长得非常的丑。。。
使用tk的clam主题以后感觉稍微好了一点点
就是在173行之前加上
```
self.style=Style()
self.style.theme_use('clam')
self.root.mainloop()
```
不过这会覆盖掉那个行高的缩放，行高又变成20了。。
参见：
http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/ttk-theme-layer.html

**Comment by eight04** [comment]
:+1: 能貼個比較圖嗎？另外有點 linux 上的預設 theme 是？

順便弣上 Windows 7 上的︰
```
>>> from tkinter import ttk
>>> s = ttk.Style()
>>> s.theme_names()
('winnative', 'clam', 'alt', 'default', 'classic', 'vista', 'xpnative')
>>> s.theme_use()
'vista'
>>>
```

**Comment by petronny** [comment]
'clam', 'alt', 'default', 'classic'我只有这4个。。
不过这4个感觉都和默认的有区别。。

**Comment by eight04** [comment]
已於 2016.7.1 修正
