### ISSUE TITLE
e-hentai失効了？

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#189]
我貼入連結之後出現
解析錯誤！You didn't login的訊息
但是我的setting裡面
cookie_ipb_pass_hash 
cookie_ipb_member_id 
的資料我看了應該還是沒有變

**Comment by eight04** [comment]
有更新到最新版嗎？現在登入需要一個新的 cookie，大概是 3/13 號左右的更新。

**Comment by kesdoputr** [comment]
已經更新到3.27的版本了，還是說我需要手動去設定裡頭加？

**Comment by eight04** [comment]
更新後要啟動關閉一次，新設定才會被寫進 settings.ini。

**Comment by kesdoputr** [comment]
我重開過以後setting裡頭關於e-hentai的部分還是只有下面四個
cookie_ipb_pass_hash = 
cookie_ipb_member_id = 
original = true
cookie_igneous = mystery

然後我試著丟一個連結給他出現的錯誤訊息如下

C:\Users\k7\Desktop>comiccrawler gui
Start analyzing https://exhentai.org/g/1393375/4003974d5c/
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread
at 0x03F05B28>
Traceback (most recent call last):
  File "c:\python\lib\site-packages\worker\__init__.py", line 474, in wrap_worke
r
    self.ret = self.worker(*args, **kwargs)
  File "c:\python\lib\site-packages\comiccrawler\download_manager.py", line 152,
 in analyze_thread
    Analyzer(mission).analyze()
  File "c:\python\lib\site-packages\comiccrawler\analyzer.py", line 57, in analy
ze
    self.do_analyze()
  File "c:\python\lib\site-packages\comiccrawler\analyzer.py", line 84, in do_an
alyze
    self.html, self.mission.url)
  File "c:\python\lib\site-packages\comiccrawler\mods\exh.py", line 37, in get_t
itle
    check_login(html)
  File "c:\python\lib\site-packages\comiccrawler\mods\exh.py", line 34, in check
_login
    raise PauseDownloadError("You didn't login!")
comiccrawler.error.PauseDownloadError: You didn't login!
Session saved

**Comment by eight04** [comment]
`You didn't login!` 的意思是你沒有登入。必須在設定檔中 `cookie_` 開頭的設定填入正確的登入資訊。

**Comment by bluelovers** [comment]
按 F12 可以去找 cookies

**Comment by kesdoputr** [comment]
setting裡頭cookies的那邊我有填，之前也能用，我只是貼上來的時候沒有一起把cookie那兩個複製上來，我發文的那時候才發現他跟我說沒有login

**Comment by eight04** [comment]
你有填 igneous 嗎？

**Comment by kesdoputr** [comment]
是指cookie_igneous = mystery這一項嗎？

**Comment by eight04** [comment]
是，mystery 是無法登入的值。

**Comment by kesdoputr** [comment]
把igneous貼上以後可以使用了，非常感謝m(_ _)m
