### ISSUE TITLE
不確定是算程式的問題還是網站的問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#19]
剛剛開起來看看有沒有更新，結果無限的全部都變成有更新，以悠哉日常大王為例
http://www.comicbus.com/html/7317.html
我在crawler的介面用右鍵選了"重新選擇集數"發現程式抓到了兩份重複的集數，如下圖
https://i.imgur.com/1hBLtlv.png
我的資料夾裡保留只有34-70，但是照上圖他抓到的更新方式，我直接按下載更新的話
會變成從第01-02話開始抓起(右半邊第二份的集數變成有勾上)，如果我不每一套漫畫
都重新選擇集數來把現在被勾起來的部分拿掉的話會變成全都從頭開始抓起，這部分有
辦法從程式上修正嗎？就是像圖片上那樣不知道為什麼會抓到兩份一樣的集數然後有的
部分沒勾有的部分有勾，但是程式都當成有更新。
目前crawler的情況如圖：https://i.imgur.com/hZF0xNw.png
大部分的都是其實沒有更新(有開網頁去確認過)，但是全部被判定成有新話數了。

**Comment by eight04** [comment]
猜測是網址變了。可以把集數列表傳給我嗎？在「%userprofile%\comiccrawler\pool」裡面，只要傳一個出問題的就好

kesdoputr <notifications@github.com> 於 2016年8月8日 下午5:20 寫道：

**Comment by kesdoputr** [comment]
已經寄到eight04上頭了，希望沒有弄錯。

**Comment by eight04** [comment]
第001話 13年12月
http://v.comicbus.com/online/insurance-10326.html?ch=1

第001話 13年12月
http://v.comicbus.com/online/comic-10326.html?ch=1

由於目前是以網址來辨認是否兩集為相同的集數，所以遇到這種網址不同但標題相同的情況就會兩者都保留。

或許應該把標題也考慮進去？畢竟下載資料夾也是根據標題建立的

**Comment by eight04** [comment]
已於 2016.8.8 修復
