### ISSUE TITLE
希望能增加http://dmeden.net/

### ISSUE THREAD

**Issue by qewrwerwer** [eight04/ComicCrawler#191]
九九漫华好像挂了 == 能否加多一个境像 这多条路是条路

**Comment by eight04** [comment]
原因是？有哪個漫畫是只有 eden 有的嗎？另外我現在點 www.99comic.com 被轉到 http://www.huhudm.com。

**Comment by qewrwerwer** [comment]
九九漫画网原网址早已改成http://99.hhxxee.com/  上周起已经挂掉了， http://dmeden.net/为http://99.hhxxee.com/ 的镜像站，99.hhxxee.com好像是服务器没有了

**Comment by eight04** [comment]
99.hhxxee.com 看起來又恢復了

**Comment by qewrwerwer** [comment]
99似乎不更新了 好多只有集数

**Comment by eight04** [comment]
dmeden看起來也沒了
