### ISSUE TITLE
Pixiv下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#192]
前幾天pixiv做了一次改版
現在變得沒辦法把tag連結加入任務列表
也沒辦法檢查更新已經加進圖書館裡的tag連結

以下列連結為例:
https://www.pixiv.net/member_illust.php?id=16652305&tag=%E6%9D%B1%E6%96%B9project
加入連結後:
https://drive.google.com/file/d/1fNYiRocYuj9DZTAe1Dh9S0mdhaayM8cQ/view
https://drive.google.com/file/d/1oER_Gh37oF9_BdCt_toUTiJ4AUC3jkNV/view

**Comment by chenhan200** [comment]
不好意思請問近期有空處理這個問題嗎
因為已經過了滿多天 想說會不會是您忘記了所以來提醒一下
如果是因為最近沒空處理那請無視我就好
抱歉打擾了

**Comment by eight04** [comment]
Fixed at v2019.5.3.
