### ISSUE TITLE
打開gui想看有什麼更新的時候會出現錯誤

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#195]
您好，已經更新到最新的0520版，打開gui讓他跑更新的時候會出現如圖上的錯誤
然後程式就停住了，不知道有沒有辦法解決呢？謝謝。
https://i.imgur.com/lL9QdMu.jpg

**Comment by eight04** [comment]
我於 （2019/6/25 17:23） 測試 https://www.comicbus.com/html/11309.html 正常，你可以再次確認嗎？

**Comment by kesdoputr** [comment]
回報，剛剛打開測試發現已經都正常了，可能是那時候網站有問題吧，我先把這個issue關掉了，謝謝。
