### ISSUE TITLE
希望能增加設定 每次啟動時 檢查圖館內的項目的最大數量

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#196]
希望能增加設定 每次啟動時 檢查圖館內的項目的最大數量
比如 可以設定 100 然後 啟動後就只會檢查 100個 剩下的則下次再檢查
(此功能可搭配第二點的建議

---

希望能增加檢查間隔 比如可以設定 七天 然後 該項目超過七天才檢查有沒有更新

---

另外又是蠢問題
不知道為什麼 又更新失敗了

```
C:\Program Files (Portable)\ConsoleZ>pip install --upgrade comiccrawler
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting comiccrawler
  Using cached https://files.pythonhosted.org/packages/a2/8c/8b6f98f83e7efd7349f04abb3f6d5f5d97a49ff965a6ce262bb2bc8f3999/comiccrawler-2019.5.20.tar.gz
Collecting belfrywidgets~=1.0 (from comiccrawler)
  Using cached https://files.pythonhosted.org/packages/82/e8/0e06d2b22bab08089e8a3f2b337cb8665395d49e57251d1bdd8549914a22/belfrywidgets-1.0.3-py2.py3-none-any.whl
Collecting desktop3~=0.5.2 (from comiccrawler)
  Downloading https://files.pythonhosted.org/packages/2c/1c/3691a13d4a0104f981b6d1e79a26e8883047c9174b82432f671296100075/desktop3-0.5.2.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\pip-install-i8fit_\desktop3\setup.py", line 21, in <module>
        long_description = read("README.rst"),
      File "c:\users\user\appdata\local\temp\pip-install-i8fit_\desktop3\setup.py", line 11, in read
        with open(path.join(here, file), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-i8fit_\desktop3\

```

**Comment by eight04** [comment]
> 希望能增加設定 每次啟動時 檢查圖館內的項目的最大數量
> 比如 可以設定 100 然後 啟動後就只會檢查 100個 剩下的則下次再檢查

原因是？

> 希望能增加檢查間隔 比如可以設定 七天 然後 該項目超過七天才檢查有沒有更新

這個應該可行

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

你安裝了舊版的 Python。Comic Crawler 需要 3.4 以上。見 https://github.com/eight04/ComicCrawler#install-python

**Comment by bluelovers** [comment]
連續檢查兩千多個網頁 感覺不是什麼好現象XD
雖然實際上對電腦與網速沒有影響就是

而且短時間內大量檢查網頁 感覺上就有點不太好
(雖然下載的時候 就沒再考慮這種事情就是 但如果只是檢查更新 我覺得不需要一次檢查那麼多)

**Comment by IthildinX** [comment]
覆議，像manhuagui大量連線時會有一陣子被BAN IP無法連線，
如果能設定最近幾天內更新過的暫時不檢查更新可能會有點幫助

**Comment by eight04** [comment]
你的意思類似下面的功能嗎？

1. 有編號 1~1000 的任務
2. 第一天檢查第 1~100 個
3. 第二天檢查第 101~200 個
4. ...
5. 第十天檢查第 901~1000 個

但平均下來，這和十天內全部檢查一次是一樣的意思。如果增加一個新設定 `autocheck_interval`，能符合你的用途嗎？

> 像manhuagui大量連線時會有一陣子被BAN IP無法連線

這應該開另一個 issue

> 設定最近幾天內更新過的暫時不檢查更新

這個功能平均下來也和 `autocheck_interval` 的效果差不多。不過它可以對 module 各別設定，也許值得加入？

**Comment by IthildinX** [comment]
我覺得可能針對manhuagui要有個檢查間隔，避免每次檢查更新的時候就大量存取掃過去，
例如說就算手動點檢查更新的時候，一樣會避免去重複檢查當天才更新過的內容之類的
> 希望能增加檢查間隔 比如可以設定 七天 然後 該項目超過七天才檢查有沒有更新
類似這個要求吧，某次改版之後圖書館那邊多了更新的日期，可以拿來當判斷避免重複檢查的依據?

**Comment by eight04** [comment]
> 目前好像只有漫畫櫃比較會避免大量連線，能根據不同模組做設定的話應該是比較好

該設定無法避免大量連線。只要使用者七天內不啟動 Comic Crawler，七天後再啟動，所有的任務全都會被更新。

**Comment by bluelovers** [comment]
覺得限制每次啟動時檢查的最大數量會比較好一點

(同一天內 可以多次重開 來觸發更新那些還未檢查的部分 以及 手動按下檢查更新時也會觸發更新這樣 不需要去檢查今天是否已經開過)

不然就會像上面所說 X 天沒開 結果一開導致檢查全部更新

**Comment by IthildinX** [comment]
> > 目前好像只有漫畫櫃比較會避免大量連線，能根據不同模組做設定的話應該是比較好
> 
> 該設定無法避免大量連線。只要使用者七天內不啟動 Comic Crawler，七天後再啟動，所有的任務全都會被更新。

七天沒開一口氣全刷新可能沒什麼問題，
我比較容易爆掉的是反而太勤快，每天都手動全刷新，大概第四第五天就會撞到上限
然後會有一陣子都需要想辦法跳IP

**Comment by eight04** [comment]
> 覺得限制每次啟動時檢查的最大數量會比較好一點

原因是？如果只是感覺不好的話我不會加入這個功能。如果是像 @IthildinX 大量連線造成被 block 的狀況，則必須從連線方面去著手，而不是去新增一個更複雜的更新機制。

在 #204 中，我把檢查更新的間隔放進設定檔裡了，預設是 24 小時。

**Comment by bluelovers** [comment]
大量檢查更新就會相對增加 哪一天可能就因此多出阻擋機制的機會
個人使用會覺得沒什麼 但 假設有十幾個 上百個人 甚至更多 都擁有大量的圖書館清單

每個人啟動時都檢查大量網頁(以我來說清單內就有兩三千個) 相對就變成間接性的ddos之類感覺
這也對於提供服務的網站來說造成不必要的負擔
(雖然對於那些網站而言 這點小 case 連問題都算不上就是)

但還是有可能被列入阻擋機制之內
例如 上面 @IthildinX 所說 漫畫櫃有阻擋機制存在

搞不好哪天就多出了不用等他連續N天都檢查一堆才鎖
而是還沒檢查完 就已經被鎖

而做成通用設定的話
將來即使要做成每個模組下也能覆蓋通用設定 也比較簡單一點

**Comment by eight04** [comment]
你說的這些原因是正在發生、曾發生過、有數據支持的嗎？我不是很想寫程式去解決沒有發生的問題（而且也不確定該功能是否可以解決該問題）。

關於漫畫櫃，其實以前只要檢查 30 項任務就會被 Ban 了。現在不會那麼快被 Ban 是調整過的結果︰
https://github.com/eight04/ComicCrawler/pull/116
https://github.com/eight04/ComicCrawler/pull/132

**Comment by bluelovers** [comment]
沒有 純粹腦補 那就先忽略這個吧

有天數間隔這點 也是夠了
