### ISSUE TITLE
希望能增加 下載失敗超過一定次數 就忽略 跳至下載下一個項目

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#199]
希望能增加 下載失敗超過一定次數 就忽略 跳至下載下一個項目 (例如 三次)
並且直到下次重新開啟程式之前 都不再嘗試下載

因為有時候 pixiv 會有那種 似乎已經在伺服器消失的圖片
但仍然會被解析出來 導致 會因為下載不成功 而無線迴圈 

也會造成變成 需要刪除該作者的連結 才能正常下載其他的

**Comment by eight04** [comment]
目前已經有「重試太多次就跳過任務」的功能，見︰
https://github.com/eight04/ComicCrawler/blob/07eed5d1c3f667503623ef1876f8121c181fba68/comiccrawler/crawler.py#L327-L328

`limit` 預設是 10。也許可以它放到設定檔裡讓使用者自訂。

另外，之前 Pixiv 模組其實有「遇到無法下載的圖時自動跳過該illust_id」的機制︰
https://github.com/eight04/ComicCrawler/blob/07eed5d1c3f667503623ef1876f8121c181fba68/comiccrawler/mods/pixiv.py#L163-L167

問題是，若登入檢查出了問題（例︰ComicCrawler 測試登入成功，但使用者又在網頁登出；或是 Pixiv 改版），那麼該機制就會造成反效果︰

1. 所有圖都會被跳過。因為使用者沒登入，所有圖都下載失敗
2. 因為所有圖都被跳過，該任務會被標示為下載成功

所以該機制就被暫時移除了。

**Comment by bluelovers** [comment]
改成不標示成功 而是標示為擱置/忽略之類
然後 等到下次檢查更新或者重開 才會再度嘗試 如何?

**Comment by eight04** [comment]
> 等到下次檢查更新 ... 才會再度嘗試

這個機制和更新無關，是下載圖片時的機制。

現狀就是不再把任務標示成功。失敗十次後便會被跳過。

**Comment by eight04** [comment]
#202 重新新增了 error handler。但這次只對 404 錯誤生效，也就是遇到被刪除的圖片就會直接跳過不重試。
