### ISSUE TITLE
感謝作者

### ISSUE THREAD

**Issue by j129008** [eight04/ComicCrawler#2]
可以支援e紳士實在太棒了(?)
不過 右鍵 "重新選擇級數" 的部分似乎有問題
重新選擇後沒辦法再下載
希望可以更新

by the way, 我看到threading的部分
https://github.com/j129008/ComicCrawler/blob/master/comiccrawler.py#L378
弄了4個waitChild, 有沒有可能讓這部份能夠快一些(不要wait)
已經花了時間看, 不過我還是不太知道怎麽下手讓他下載速度變快
能不能給一下提示?

**Comment by eight04** [comment]
重新選擇集數的 Bug 其實已經放在 Todo 裡了，不過我還沒修

`waitChild` 會呼叫函式並等待它完成，而函式就是傳入的第一個變數，分別是
```
grabhtml	- 下載 HTML 檔
downloader.getimgurl	- 分析找出圖片連結
downloader.getnextpageurl - 分析找出下一頁的連結
grabimg - 下載圖片檔
```
(可以參考 [worker.py](https://github.com/j129008/ComicCrawler/blob/master/worker.py#L350))
所以其實是沒有額外等待時間的
