### ISSUE TITLE
ex站倒了，eh站有些链接没法解析。

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#207]
例如： e-hentai.org/g/667838/3b82aa82d5/
这个会给一个内容提示，然后解析不了。
ex直接没发链接，他也关站了。
e站没了，n站可以加进解析列表吗。
谢谢您！

**Comment by chenhan200** [comment]
ex站復活了
雖然可以加連結進任務列表，但分析出來的集數是錯的
並且無法下載

**Comment by starobots** [comment]
重新上线就无所谓了。
