### ISSUE TITLE
pixiv ajax 錯誤

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#209]
現在只要加入 pixiv 網址就會出現這種錯誤訊息

![image](https://user-images.githubusercontent.com/167966/61991335-1c163d00-b081-11e9-83ad-98968cccd0e7.png)

**Comment by chenhan200** [comment]
測試了一下
沒辦法加入一般的連結，舊有的連結檢查更新也會出錯
但如果是tag連結的話就沒問題，可以加入任務列表也可以檢查更新
以下面連結為例：
無法加入　https://www.pixiv.net/member_illust.php?id=12452172
可以加入　https://www.pixiv.net/member_illust.php?id=12452172&tag=3DCG

**Comment by bluelovers** [comment]
我猜測應該是 現在的 pixiv 要求要有 work_category=illustManga 所以才會出錯

**Comment by chenhan200** [comment]
抱歉想請教下該怎麼導入您寫的修正檔
https://github.com/bluelovers/ComicCrawler/tree/patch-2
是把這頁面的東西按 Clone or download 下載下來，解壓縮後用cmd導入嗎?

**Comment by bluelovers** [comment]
你看 pr 裏面下方 作者 的回應 有說怎樣安裝
不過要記得先關掉防毒 免得防毒太貼心  自動給你擋住

**Comment by chenhan200** [comment]
https://i.imgur.com/oxmp0NM.png
看起來失敗了，不知道是哪邊出問題

**Comment by chenhan200** [comment]
犯蠢了，原來是少打一個 .
現在正在跑更新，謝謝你提供的修正檔
