### ISSUE TITLE
Danbooru下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#223]
以下面連結為例
https://danbooru.donmai.us/posts?tags=kuromitsu_maria+touhou

加入連結後可以抓到正確的集數
但實際上下載下來的會是:
https://danbooru.donmai.us/posts/1684677
https://danbooru.donmai.us/posts/1684676
https://danbooru.donmai.us/posts/1684675
https://danbooru.donmai.us/posts/1684674
https://danbooru.donmai.us/posts/1684673
......

會從集數中第一張圖開始往編號更小的圖片不停下載
並且載下來的圖片檔名尾碼會從001開始遞增:
https://i.imgur.com/x9kXWfq.png

**Comment by eight04** [comment]
看起來是 Danbooru 在圖片頁面加了換頁按鈕導致誤判了

**Comment by eight04** [comment]
Fixed at v2019.10.28.
