### ISSUE TITLE
[suggestion]  zip & delete original file

### ISSUE THREAD

**Issue by kuanyui** [eight04/ComicCrawler#23]

**Comment by eight04** [comment]
I think using 3rd-party program is much better than writing in python ourselves. It is possible to call 7-zip or other archiver with `runafterdownload` setting.

**Comment by kuanyui** [comment]
This function is very important for me, because zip file can be read by nearly all comic readers (e.g. `Comix`) ,which can jump between chapters/books/episodes files easily and conveniently. Also zip save disk space, efficient for copy.

On Linux, I call `zip` directly and easily, but I have no programming experience on Windows and don't know how to do this.

**Comment by starobots** [comment]
just write a bat, that's easy so zip files.

for /d %%X in (*) do "D:\7-zip\7z.exe" a "%%X.zip" "%%X\"

**Comment by kuanyui** [comment]
How about this https://docs.python.org/3/library/zipfile.html

**Comment by eight04** [comment]
I can write a .py script to compress folder if you need one.

Actually, I had thought if we can make Comic Crawler support archive completely, which means, to read/write images from/to archives instead of the file system. But it is not a necessary feature for me.

**Comment by kuanyui** [comment]
>I can write a .py script to compress folder if you need one.

Don't you want integrate auto-compress & delete-original-file features into ComicCrawler?

>Actually, I had thought if we can make Comic Crawler support archive completely, which means, to read/write images from/to archives instead of the file system. But it is not a necessary feature for me.

I also feel that sounds a unnecessary feature.

**Comment by eight04** [comment]
> Don't you want integrate auto-compress & delete-original-file features into ComicCrawler?

While this function can be done in one line, I won't try to re-implement it.

Also duplicate test is not only depending on the file name but the checksum.

**Comment by kuanyui** [comment]
>> Don't you want integrate auto-compress & delete-original-file features into ComicCrawler?

>While this function can be done in one line, I won't try to re-implement it.

You mean run a script which only with one line manually to zip? I exactly know, I also do like that after downloading all files with ComicCrawler currently. 

In my usage case, I need the outputted zip files only, and delete all the original directory & files to save spaces and optimize afterward transferring speed. However, that means ComicCrawler don't know what has downloaded.

>Also duplicate test is not only depending on the file name but the checksum.

How about a mechanism like following pseudo code:

```python
# After getting book/chapters title & download links
if (os.path.exist(chapter_name + ".zip")):
    pass    # Assume the file has been fully downloaded, so just ignore it.
else:
    # Current ComicCrawler's (download + check filename + checksume) mechanism
    # ......
    # After a directory fully downloaded
    if mod.config.get("zip_after_download") == true:
        zip_file(chapter_dir)
        if mod.config.get("delete_original_after_zip"):
            shutil.rmtree(chapter_dir)
```

**Comment by eight04** [comment]
Do you use CLI instead of GUI? By using GUI, Comic Crawler saves mission state in a json file (~/comiccrawler/pool/). There is no need to analyze file trees.

**Comment by kuanyui** [comment]
Oops...Yes, I run ComicCrawler on a NAS via ssh.

**Comment by eight04** [comment]
I don't use NAS. Can NAS run the GUI version?

**Comment by kuanyui** [comment]
Yes (it's just a VM running Ubuntu), but that means its hard to access via SSH.

Hmm... I think I should implement this feature, by making a wrapper of ComicCrawler. I'm planning to make ComicCrawler as a simple private web service, which is conveniently accessible for my Andriod devices.

**Comment by eight04** [comment]
I know that some download manager can launch a RPC server like [aria2](https://aria2.github.io/), It shouldn't be too hard by wrapping `comiccrawler.download_manager` like `comiccrawler.gui` does.

Or maybe it is easier to just make CLI launch mission_manager and use the saved data from it.
