### ISSUE TITLE
Sankaku下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#230]
https://chan.sankakucomplex.com/?tags=rak_%28kuraga%29
加入連結後分析到第101頁時會出錯
![20191114_sankaku](https://user-images.githubusercontent.com/30958086/68852343-a78c0a80-0712-11ea-8c69-c68c4856e12b.png)
<pre><code>Start analyzing https://chan.sankakucomplex.com/?tags=rak_%28kuraga%29
Analyzing https://chan.sankakucomplex.com/?next=18385301&tags=rak_%28kuraga%29&p
age=2...
Analyzing https://chan.sankakucomplex.com/?next=18209710&tags=rak_%28kuraga%29&p
age=3...
Analyzing https://chan.sankakucomplex.com/?next=18209337&tags=rak_%28kuraga%29&p
age=4...
Analyzing https://chan.sankakucomplex.com/?next=18206152&tags=rak_%28kuraga%29&p
age=5...
Analyzing https://chan.sankakucomplex.com/?next=18205793&tags=rak_%28kuraga%29&p
age=6...
Analyzing https://chan.sankakucomplex.com/?next=17854196&tags=rak_%28kuraga%29&p
age=7...
Analyzing https://chan.sankakucomplex.com/?next=17829442&tags=rak_%28kuraga%29&p
age=8...
Analyzing https://chan.sankakucomplex.com/?next=17824891&tags=rak_%28kuraga%29&p
age=9...
Analyzing https://chan.sankakucomplex.com/?next=17824557&tags=rak_%28kuraga%29&p
age=10...
Analyzing https://chan.sankakucomplex.com/?next=17823596&tags=rak_%28kuraga%29&p
age=11...
Analyzing https://chan.sankakucomplex.com/?next=17822495&tags=rak_%28kuraga%29&p
age=12...
Analyzing https://chan.sankakucomplex.com/?next=17818651&tags=rak_%28kuraga%29&p
age=13...
Analyzing https://chan.sankakucomplex.com/?next=17564517&tags=rak_%28kuraga%29&p
age=14...
Analyzing https://chan.sankakucomplex.com/?next=17559465&tags=rak_%28kuraga%29&p
age=15...
Analyzing https://chan.sankakucomplex.com/?next=17559444&tags=rak_%28kuraga%29&p
age=16...
Analyzing https://chan.sankakucomplex.com/?next=17559424&tags=rak_%28kuraga%29&p
age=17...
Analyzing https://chan.sankakucomplex.com/?next=17384455&tags=rak_%28kuraga%29&p
age=18...
Analyzing https://chan.sankakucomplex.com/?next=17359120&tags=rak_%28kuraga%29&p
age=19...
Analyzing https://chan.sankakucomplex.com/?next=17359099&tags=rak_%28kuraga%29&p
age=20...
Analyzing https://chan.sankakucomplex.com/?next=17331428&tags=rak_%28kuraga%29&p
age=21...
Analyzing https://chan.sankakucomplex.com/?next=16707484&tags=rak_%28kuraga%29&p
age=22...
Analyzing https://chan.sankakucomplex.com/?next=16040309&tags=rak_%28kuraga%29&p
age=23...
Analyzing https://chan.sankakucomplex.com/?next=16039082&tags=rak_%28kuraga%29&p
age=24...
Analyzing https://chan.sankakucomplex.com/?next=16038065&tags=rak_%28kuraga%29&p
age=25...
Analyzing https://chan.sankakucomplex.com/?next=16036788&tags=rak_%28kuraga%29&p
age=26...
Analyzing https://chan.sankakucomplex.com/?next=16035742&tags=rak_%28kuraga%29&p
age=27...
Analyzing https://chan.sankakucomplex.com/?next=15991693&tags=rak_%28kuraga%29&p
age=28...
Analyzing https://chan.sankakucomplex.com/?next=15894127&tags=rak_%28kuraga%29&p
age=29...
Analyzing https://chan.sankakucomplex.com/?next=15855537&tags=rak_%28kuraga%29&p
age=30...
Analyzing https://chan.sankakucomplex.com/?next=15773863&tags=rak_%28kuraga%29&p
age=31...
Analyzing https://chan.sankakucomplex.com/?next=15699876&tags=rak_%28kuraga%29&p
age=32...
Analyzing https://chan.sankakucomplex.com/?next=15658649&tags=rak_%28kuraga%29&p
age=33...
Analyzing https://chan.sankakucomplex.com/?next=15602758&tags=rak_%28kuraga%29&p
age=34...
Analyzing https://chan.sankakucomplex.com/?next=15508578&tags=rak_%28kuraga%29&p
age=35...
Analyzing https://chan.sankakucomplex.com/?next=15262341&tags=rak_%28kuraga%29&p
age=36...
Analyzing https://chan.sankakucomplex.com/?next=14163315&tags=rak_%28kuraga%29&p
age=37...
Analyzing https://chan.sankakucomplex.com/?next=13977648&tags=rak_%28kuraga%29&p
age=38...
Analyzing https://chan.sankakucomplex.com/?next=13856891&tags=rak_%28kuraga%29&p
age=39...
Analyzing https://chan.sankakucomplex.com/?next=13355665&tags=rak_%28kuraga%29&p
age=40...
Analyzing https://chan.sankakucomplex.com/?next=13353212&tags=rak_%28kuraga%29&p
age=41...
Analyzing https://chan.sankakucomplex.com/?next=13350587&tags=rak_%28kuraga%29&p
age=42...
Analyzing https://chan.sankakucomplex.com/?next=13157437&tags=rak_%28kuraga%29&p
age=43...
Analyzing https://chan.sankakucomplex.com/?next=13154651&tags=rak_%28kuraga%29&p
age=44...
Analyzing https://chan.sankakucomplex.com/?next=12880460&tags=rak_%28kuraga%29&p
age=45...
Analyzing https://chan.sankakucomplex.com/?next=12668679&tags=rak_%28kuraga%29&p
age=46...
Analyzing https://chan.sankakucomplex.com/?next=12394647&tags=rak_%28kuraga%29&p
age=47...
Analyzing https://chan.sankakucomplex.com/?next=12352188&tags=rak_%28kuraga%29&p
age=48...
Analyzing https://chan.sankakucomplex.com/?next=12056898&tags=rak_%28kuraga%29&p
age=49...
Analyzing https://chan.sankakucomplex.com/?next=11874107&tags=rak_%28kuraga%29&p
age=50...
Analyzing https://chan.sankakucomplex.com/?next=11697154&tags=rak_%28kuraga%29&p
age=51...
Analyzing https://chan.sankakucomplex.com/?next=11536357&tags=rak_%28kuraga%29&p
age=52...
Analyzing https://chan.sankakucomplex.com/?next=11479441&tags=rak_%28kuraga%29&p
age=53...
Analyzing https://chan.sankakucomplex.com/?next=11417586&tags=rak_%28kuraga%29&p
age=54...
Analyzing https://chan.sankakucomplex.com/?next=11241711&tags=rak_%28kuraga%29&p
age=55...
Analyzing https://chan.sankakucomplex.com/?next=11167422&tags=rak_%28kuraga%29&p
age=56...
Analyzing https://chan.sankakucomplex.com/?next=11031007&tags=rak_%28kuraga%29&p
age=57...
Analyzing https://chan.sankakucomplex.com/?next=10846639&tags=rak_%28kuraga%29&p
age=58...
Analyzing https://chan.sankakucomplex.com/?next=10656641&tags=rak_%28kuraga%29&p
age=59...
Analyzing https://chan.sankakucomplex.com/?next=10282985&tags=rak_%28kuraga%29&p
age=60...
Analyzing https://chan.sankakucomplex.com/?next=9774509&tags=rak_%28kuraga%29&pa
ge=61...
Analyzing https://chan.sankakucomplex.com/?next=9623878&tags=rak_%28kuraga%29&pa
ge=62...
Analyzing https://chan.sankakucomplex.com/?next=9619215&tags=rak_%28kuraga%29&pa
ge=63...
Analyzing https://chan.sankakucomplex.com/?next=9598056&tags=rak_%28kuraga%29&pa
ge=64...
Analyzing https://chan.sankakucomplex.com/?next=9473676&tags=rak_%28kuraga%29&pa
ge=65...
Analyzing https://chan.sankakucomplex.com/?next=9376667&tags=rak_%28kuraga%29&pa
ge=66...
Analyzing https://chan.sankakucomplex.com/?next=9363420&tags=rak_%28kuraga%29&pa
ge=67...
Analyzing https://chan.sankakucomplex.com/?next=9363158&tags=rak_%28kuraga%29&pa
ge=68...
Analyzing https://chan.sankakucomplex.com/?next=9363041&tags=rak_%28kuraga%29&pa
ge=69...
retry after 5 seconds
retry after 10 seconds
retry after 20 seconds
retry after 40 seconds
Analyzing https://chan.sankakucomplex.com/?next=9341060&tags=rak_%28kuraga%29&pa
ge=70...
Analyzing https://chan.sankakucomplex.com/?next=9155681&tags=rak_%28kuraga%29&pa
ge=71...
Analyzing https://chan.sankakucomplex.com/?next=8942557&tags=rak_%28kuraga%29&pa
ge=72...
Analyzing https://chan.sankakucomplex.com/?next=8718389&tags=rak_%28kuraga%29&pa
ge=73...
Analyzing https://chan.sankakucomplex.com/?next=8568439&tags=rak_%28kuraga%29&pa
ge=74...
Analyzing https://chan.sankakucomplex.com/?next=8160718&tags=rak_%28kuraga%29&pa
ge=75...
Analyzing https://chan.sankakucomplex.com/?next=8156680&tags=rak_%28kuraga%29&pa
ge=76...
Analyzing https://chan.sankakucomplex.com/?next=8154416&tags=rak_%28kuraga%29&pa
ge=77...
Analyzing https://chan.sankakucomplex.com/?next=7962859&tags=rak_%28kuraga%29&pa
ge=78...
Analyzing https://chan.sankakucomplex.com/?next=7922334&tags=rak_%28kuraga%29&pa
ge=79...
Analyzing https://chan.sankakucomplex.com/?next=7855900&tags=rak_%28kuraga%29&pa
ge=80...
Analyzing https://chan.sankakucomplex.com/?next=7824394&tags=rak_%28kuraga%29&pa
ge=81...
Analyzing https://chan.sankakucomplex.com/?next=7777915&tags=rak_%28kuraga%29&pa
ge=82...
Analyzing https://chan.sankakucomplex.com/?next=7766443&tags=rak_%28kuraga%29&pa
ge=83...
Analyzing https://chan.sankakucomplex.com/?next=7764668&tags=rak_%28kuraga%29&pa
ge=84...
Analyzing https://chan.sankakucomplex.com/?next=7764482&tags=rak_%28kuraga%29&pa
ge=85...
Analyzing https://chan.sankakucomplex.com/?next=7764391&tags=rak_%28kuraga%29&pa
ge=86...
Analyzing https://chan.sankakucomplex.com/?next=7764308&tags=rak_%28kuraga%29&pa
ge=87...
Analyzing https://chan.sankakucomplex.com/?next=7737825&tags=rak_%28kuraga%29&pa
ge=88...
Analyzing https://chan.sankakucomplex.com/?next=7652374&tags=rak_%28kuraga%29&pa
ge=89...
Analyzing https://chan.sankakucomplex.com/?next=7533331&tags=rak_%28kuraga%29&pa
ge=90...
Analyzing https://chan.sankakucomplex.com/?next=7482088&tags=rak_%28kuraga%29&pa
ge=91...
Analyzing https://chan.sankakucomplex.com/?next=7380281&tags=rak_%28kuraga%29&pa
ge=92...
Analyzing https://chan.sankakucomplex.com/?next=7379030&tags=rak_%28kuraga%29&pa
ge=93...
Analyzing https://chan.sankakucomplex.com/?next=7378996&tags=rak_%28kuraga%29&pa
ge=94...
Analyzing https://chan.sankakucomplex.com/?next=7366839&tags=rak_%28kuraga%29&pa
ge=95...
Analyzing https://chan.sankakucomplex.com/?next=7169098&tags=rak_%28kuraga%29&pa
ge=96...
Analyzing https://chan.sankakucomplex.com/?next=7150663&tags=rak_%28kuraga%29&pa
ge=97...
Analyzing https://chan.sankakucomplex.com/?next=7104664&tags=rak_%28kuraga%29&pa
ge=98...
Analyzing https://chan.sankakucomplex.com/?next=7047174&tags=rak_%28kuraga%29&pa
ge=99...
retry after 5 seconds
retry after 10 seconds
retry after 20 seconds
retry after 40 seconds
Analyzing https://chan.sankakucomplex.com/?next=7020421&tags=rak_%28kuraga%29&pa
ge=100...
Analyzing https://chan.sankakucomplex.com/?next=6995193&tags=rak_%28kuraga%29&pa
ge=101...
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread
at 0x032F96F0>
Traceback (most recent call last):
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\analyzer.py", line 137, in analyze_pages
    self.html = self.grabber.html(url, retry=True)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\module_grabber.py", line 17, in html
    **kwargs
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\grabber.py", line 151, in grabhtml
    r = grabber(*args, **kwargs)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\grabber.py", line 105, in grabber
    r = await_(do_request, s, url, proxies, retry, **kwargs)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\worker\__init__.py", line 682, in get
    raise err
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\comiccrawler\grabber.py", line 131, in do_request
    r.raise_for_status()
  File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
es\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan
.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20h
ttp://chan.sankakucomplex.com/post/error
Session saved
</code></pre>

**Comment by eight04** [comment]
看起來 Beta 版沒有這個限制
