### ISSUE TITLE
Sankaku任務命名規則

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#234]
加入 Sankaku 原版網址跟 Beta 版網址，所產生的任務名稱不一樣
以下面的連結為例
原版：
https://chan.sankakucomplex.com/?tags=namaniku_atk+soukou_akki_muramasa
[sankaku] namaniku atk + soukou akki muramasa
Beta 版：
https://beta.sankakucomplex.com/?tags=namaniku_atk+soukou_akki_muramasa
[sankaku] namaniku_atk soukou_akki_muramasa

希望能將 Beta 版 的任務命名規則改成跟原版的一致

**Comment by eight04** [comment]
根據你舉的例子，我反而覺得把原版的名字改成類似 beta 版的會更好。

**Comment by chenhan200** [comment]
主要是因為已經建立幾百個 sankaku 的任務了
希望以後用 beta 版新建的任務能跟舊任務的命名規則一致
另外如果想刪除舊任務，改用 beta 版連結進行圖書館更新
也可以沿用舊資料夾，而不用去更改資料夾名稱

**Comment by eight04** [comment]
那我建議寫個程式把舊版的名字改成 beta 版的。所有的任務都存在圖書館嗎？

**Comment by chenhan200** [comment]
很抱歉回覆晚了
確實所有任務都存在圖書館裡
不過關於命名方式，個人還有一個建議
就是不知是否可以保留+號，以上面的例子來說，會變成：
namaniku_atk + soukou_akki_muramasa
因為現在beta版的命名方式是只用一個半形空格隔開
私以為這樣間距過小，並不是很方便用肉眼辨視
故希望新命名規則可以繼續沿用這部分

**Comment by eight04** [comment]
我傾向於保留網頁傳給使用者的原始資料。舊版的任務名稱來自網頁的 title，也就是頁籤上顯示的標題；beta 版則是直接反映 URL 中的 tags。

注意，tags 並不是單純的一串以空白分隔的英文單字，其中的符號是有意義的︰
https://chan.sankakucomplex.com/wiki/show?title=help%3A_advanced_search_guide

使用原始資料也保證了向上兼容性。

----

批次改名可以用這個程式（別忘了備份）︰
```py
import re
import pathlib

from comiccrawler.config import config
from comiccrawler.mission_manager import mission_manager
from comiccrawler.episode_loader import edit_mission_id
from comiccrawler.mods import sankaku_beta
from comiccrawler import profile
from comiccrawler.util import safefilepath

config.load()
mission_manager.load()

save_path = pathlib.Path(profile.get(config.config.get("Sankaku", "savepath")))

for mission in mission_manager.get_all("library"):
  if re.search("chan\.sankakucomplex\.com/\?tags=.+", mission.url):
    with edit_mission_id(mission):
      old_title = mission.title
      new_title = sankaku_beta.get_title(None, mission.url)
      
      print("{} -> {}".format(mission.title, new_title))
      
      # rename mission
      mission.title = new_title
      
      # rename folder
      old_folder = save_path / safefilepath(old_title)
      new_folder = save_path / safefilepath(new_title)
      old_folder.rename(new_folder)
    
mission_manager.edit = True
mission_manager.save()

```

**Comment by chenhan200** [comment]
不好意思，想請問上面的程式碼該怎麼使用
貼到記事本存檔，副檔名改bat然後直接執行就好嗎？

**Comment by eight04** [comment]
這是 python 程式。副檔名是 .py

**Comment by chenhan200** [comment]
剛才測試了一下
321個資料夾中，只有5個有成功修改到
![Sankaku_Rename](https://user-images.githubusercontent.com/30958086/69897911-262cad00-138d-11ea-8ef4-7f13df0ee4c8.png)

以下附上在這之後執行批次檔時出現的錯誤訊息：
![Sankaku_Rename_cmd](https://user-images.githubusercontent.com/30958086/69897912-2a58ca80-138d-11ea-89f8-91106a616426.png)

**Comment by eight04** [comment]
你有保留第一次執行時的錯誤紀錄嗎？

> 以下附上在這之後執行批次檔時出現的錯誤訊息：
> ![Sankaku_Rename_cmd](https://user-images.githubusercontent.com/30958086/69897912-2a58ca80-138d-11ea-89f8-91106a616426.png)

我猜這是第二次執行時的錯誤紀錄。因為第一次執行到一半就錯誤，沒有存檔。第二次執行時用舊標題就找不到資料夾。

----

下面這是會忽略改名錯誤的版本︰
```py
import re
import pathlib

from comiccrawler.config import config
from comiccrawler.mission_manager import mission_manager
from comiccrawler.episode_loader import edit_mission_id
from comiccrawler.mods import sankaku_beta
from comiccrawler import profile
from comiccrawler.util import safefilepath

config.load()
mission_manager.load()

save_path = pathlib.Path(profile.get(config.config.get("Sankaku", "savepath")))

for mission in mission_manager.get_all("library"):
  if re.search("chan\.sankakucomplex\.com/\?tags=.+", mission.url):
    with edit_mission_id(mission):
      old_title = mission.title
      new_title = sankaku_beta.get_title(None, mission.url)
      
      print("{} -> {}".format(mission.title, new_title))
      
      # rename mission
      mission.title = new_title
      
      # rename folder
      old_folder = save_path / safefilepath(old_title)
      new_folder = save_path / safefilepath(new_title)
      try:
        old_folder.rename(new_folder)
      except OSError:
        print("can't rename folder")
        pass
    
mission_manager.edit = True
mission_manager.save()
```

**Comment by chenhan200** [comment]
抱歉沒存到第一次執行時的訊息
因為他開始執行後只有一瞬間就自動關掉了

**Comment by chenhan200** [comment]
附上這次執行完的結果：
![Sankaku_Rename2](https://user-images.githubusercontent.com/30958086/69905067-eb0c9700-13e9-11ea-8d2b-86297626cb00.png)

不知為何還是有幾個資料夾沒改到
不過因為數量很少，手動修改即可
謝謝您的幫忙

**Comment by eight04** [comment]
補充一下保留cmd視窗的方法︰

1. 打開你存放程式的資料夾。舉例︰如果你把程式存成 `D:\Program\rename-sankaku.py`，就打開 `D:\Program` 資料夾。
2. 手動啟動 cmd︰在資料夾的路徑列中（快捷鍵 Alt+D）輸入 `cmd`，按 Enter。
3. 在 cmd 中，輸入 `py <檔案名>`，按 Enter。用前面的例子就是 `py rename-sankaku.py`。
4. 這樣程式結束時視窗就不會整個跳掉，而是返回剛才手動啟動的 cmd。
