### ISSUE TITLE
希望可以考慮一下新增twitter

### ISSUE THREAD

**Issue by x2443120** [eight04/ComicCrawler#241]
有越來越多創作者只在twitter更新
pixiv之類的網站也直接刪除帳號的關係希望可以考慮新增

**Comment by bluelovers** [comment]
恩 例如 https://twitter.com/MGMG_1012/media 也是

**Comment by chenhan200** [comment]
雖然還不知道是否會新增分析twitter的功能
不過如果可以的話，圖片的命名規則希望能參照下面這個擴充功能的
https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by starobots** [comment]
好像twitter换新layout了，要登陆帐号才能看media的内容。

**Comment by eight04** [comment]
#307 新增了 twitter 模組。在設定中要輸入 curl︰

1. 開啟某使用者的 twitter 主頁
2. 按 F12，開啟 network 面板，按 F5 重新整理
3. 尋找 UserTweet 或 UserMedia 的 request
4. 右鍵 > 複製 > 複製 curl (POSIX)

![image](https://user-images.githubusercontent.com/1324510/130579002-08637012-945f-40db-8ece-066fab2f822f.png)

**Comment by bluelovers** [comment]
> #307 新增了 twitter 模組。在設定中要輸入 curl︰
> 
> 1. 開啟某使用者的 twitter 主頁
> 2. 按 F12，開啟 network 面板，按 F5 重新整理
> 3. 尋找 UserTweet 或 UserMedia 的 request
> 4. 右鍵 > 複製 > 複製 curl (POSIX)
> 
> ![image](https://user-images.githubusercontent.com/1324510/130579002-08637012-945f-40db-8ece-066fab2f822f.png)

@eight04 

搞不懂怎用

==================

只複製網址的話 可以出現在出入框 但解析失敗

https://twitter.com/i/api/graphql/aWplnS7MLneppIH977wpgQ/UserMedia?variables=%7B%22userId%22%3A%221111964776169562112%22%2C%22count%22%3A20%2C%22withTweetQuoteCount%22%3Afalse%2C%22includePromotedContent%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Afalse%2C%22withUserResults%22%3Atrue%2C%22withBirdwatchPivots%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Afalse%2C%22withClientEventToken%22%3Afalse%2C%22withBirdwatchNotes%22%3Afalse%2C%22withVoice%22%3Atrue%7D

![image](https://user-images.githubusercontent.com/167966/136695261-04649f5e-cd12-484f-bb44-60925303f12a.png)

![image](https://user-images.githubusercontent.com/167966/136695282-d197cd28-6a08-4436-a9c5-1f57e3e10a61.png)

=======================

複製 curl 的話 又變成無法辨識模組
curl 複製之後 有要在處理過什麼地方嗎?



![image](https://user-images.githubusercontent.com/167966/136695074-b40bed66-c00e-422c-9f17-30611acc8a96.png)

![image](https://user-images.githubusercontent.com/167966/136695443-2be42779-551c-434a-aee9-89867618075b.png)


![image](https://user-images.githubusercontent.com/167966/136695396-ecdfc5c2-189e-4698-afd6-968657071df9.png)


![image](https://user-images.githubusercontent.com/167966/136695340-2dbcc0b4-1162-4e1a-9bd3-d37a08d68db5.png)

**Comment by eight04** [comment]
1. 更新到最新版
2. 設定檔應該類似這樣︰
  ![image](https://user-images.githubusercontent.com/1324510/152338192-be594105-af2b-4d47-a068-b9c396e34b31.png)
3. 不要把 API 貼進任務管理器。目前只支援 `https://twitter.com/xxx` 和 `https://twitter.com/xxx/media`
4. 有跟原 PO 不同的問題時，開一個新 issue 不要直接回覆。避免文不對題。
