### ISSUE TITLE
能設定失敗時 嘗試下載的次數限制嗎?

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#250]
能設定失敗時 嘗試下載的次數限制嗎?

ig 很容易出現 有些連結下載失敗
然後不斷一直重新嘗試下載

雖然過一段時間之後 就會停止下載
但是......

過程中 只要新增了 在任務列表中增加其他連結
又會變成再度嘗試下載

導致變成有點類似無限迴圈一樣

所以希望能設定嘗試的次數上限
讓他提早停止下載

------

另外 當 好幾個 ig 任務都出錯時 也會因此發生循環現象

A 失敗 > 移到最底 > 執行 B
B 失敗 > 移到最底 > 執行 C
C 失敗 > 移到最底 > 執行 A

**Comment by eight04** [comment]
> 
> 
> 過程中 只要新增了 在任務列表中增加其他連結
> 又會變成再度嘗試下載

什麼意思？原本沒在下載，加入新連結後下載會自動開始？

> A 失敗 > 移到最底 > 執行 B
> B 失敗 > 移到最底 > 執行 C
> C 失敗 > 移到最底 > 執行 A

也許可以加一個「失敗上限」的設定？例︰上限設成10 -> 10次任務失敗後停止下載

**Comment by bluelovers** [comment]
> 什麼意思？原本沒在下載，加入新連結後下載會自動開始？

原本已經錯誤過多次 停止下載 但加入新連結之後 又被觸發下載

**Comment by bluelovers** [comment]
不知道是不是因為這個BUG的原因 導致現在已經完全無法從IG上下載到任何圖片了

**Comment by eight04** [comment]
> 不知道是不是因為這個BUG的原因 導致現在已經完全無法從IG上下載到任何圖片了

從瀏覽器也看不到嗎？是整個帳號被封鎖？還是IP被封鎖？

**Comment by bluelovers** [comment]
> > 不知道是不是因為這個BUG的原因 導致現在已經完全無法從IG上下載到任何圖片了
> 
> 從瀏覽器也看不到嗎？是整個帳號被封鎖？還是IP被封鎖？

可以正常瀏覽 但就是無法從 ComicCrawler 下載到任何圖片了

**Comment by eight04** [comment]
那大概和這 issue 無關，請開一個新 issue 並附上錯誤訊息

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/95001097-4fdfe180-05f9-11eb-9ee3-d86544bf9a0d.png)
