### ISSUE TITLE
Danbooru下載問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#255]
[https://github.com/eight04/ComicCrawler/issues/223](https://github.com/eight04/ComicCrawler/issues/223/)
又出現了跟#223相同的問題
圖書館檢查可以抓到正確的集數
下載第一張圖片後會開始往編號遞減的圖片不停下載
且載下來的圖片檔名尾碼會從001開始遞增

**Comment by eight04** [comment]
網址？

**Comment by bluelovers** [comment]
我也有 這個網站的下載問題

顯示只有 29 頁 但卻已經下載到 775 頁
是不是在其中哪個圖片連結裡面 分析了錯誤的列表了?

![image](https://user-images.githubusercontent.com/167966/78725201-8e098a80-7961-11ea-8f7e-0443423f3089.png)

https://danbooru.donmai.us/posts?page=1&tags=nanaya_%28daaijianglin%29

**Comment by chenhan200** [comment]
抱歉忘記附上網址
https://danbooru.donmai.us/posts?tags=hater_%28hatater%29+touhou

**Comment by eight04** [comment]
Should be fixed at 2020.6.3
