### ISSUE TITLE
回報：無限動漫網站失效

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#256]
8comic無限動漫的網站，
原本都還可以，但近期發現已不能分析。
例如：
   鬼滅之刃
   https://www.comicbus.com/html/14132.html
   被束縛的芬尼爾
   https://www.comicbus.com/html/13737.html

想要透過「加入網址」來分析，都會跳出錯誤視窗，上面寫：
    解析錯誤！
    'NoneType' object has no attribute 'group'
有空的話請幫忙，謝謝！

**Comment by eight04** [comment]
Should be fixed in 2020.6.3

**Comment by Zivch** [comment]
Yes it did.
Thanks a lot!
