### ISSUE TITLE
部分 ig 網址會出現錯誤 無法加入

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#258]
https://www.instagram.com/aru.rinh/
https://www.instagram.com/plant.lily/
https://www.instagram.com/mimichan.259/

**Comment by eight04** [comment]
我測試正常，是什麼樣的錯誤？

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/91728307-7e6f3480-ebd5-11ea-984c-9713c2ca452b.png)

**Comment by eight04** [comment]
噢，這個 bug 可能在 2020.6.3 修掉了

**Comment by bluelovers** [comment]
```
C:\Program Files (Portable)\ConsoleZ>comiccrawler --version
2020.6.3
```

但是我用的就是 2020.6.3

**Comment by eight04** [comment]
有設定 cookie 登入嗎？

**Comment by bluelovers** [comment]
有 目前也確認過 session id 沒有變

**Comment by eight04** [comment]
console 有顯示錯誤訊息嗎？可以的話請貼上來
