### ISSUE TITLE
漫畫堆問題

### ISSUE THREAD

**Issue by forrenren** [eight04/ComicCrawler#259]
漫畫堆的網址已變更，由www.manhuadui.com變更為www.manhuabei.com 。
我已自行修改支援腳本。

但是由於漫畫堆部分漫畫“下架”，正常網頁版提示已下架，但是m.manhuabei.com可訪問並且持續更新，我自己嘗試改了很久的腳本也沒法成功，是否可以支援移動版的漫畫堆(m.manhuabei.com)？

多謝。

**Comment by eight04** [comment]
連結？

**Comment by forrenren** [comment]
> 連結？

https://m.manhuabei.com/manhua/daerwenyouxi/

例如上面的連結，（m開頭，手機版本，如果使用電腦則需要偽裝瀏覽器）訪問可以正常來看；如果使用www開頭的連結，則提示“现已屏蔽本漫画处理”。

**Comment by forrenren** [comment]
Seems Comic Crawler will no longer support this site, and the owner will not reply anymore.
