### ISSUE TITLE
漫画柜部份漫画无法读取

### ISSUE THREAD

**Issue by qewrwerwer** [eight04/ComicCrawler#260]
https://manhuagui.com/comic/30239/
比如这个 ==
估计是加了提示造成的

**Comment by IthildinX** [comment]
可以讀取，限制漫畫提示不是問題
漫畫櫃會BAN連續大量連線的IP，過陣子就好了

**Comment by eight04** [comment]
我這裡測試也正常，有沒有可能是IP問題？

**Comment by Zivch** [comment]
應該IP問題。有時被擋，把數據機關掉重開、重新抓IP位置，就又可以了。
