### ISSUE TITLE
麻煩能支持下載tvbsmh.com 的漫畫嗎， 感激

### ISSUE THREAD

**Issue by sango2001** [eight04/ComicCrawler#262]
麻煩能支持下載tvbsmh.com 的漫畫嗎， 感激

**Comment by eight04** [comment]
原因是？有什麼作品只有該站有的嗎？

**Comment by sango2001** [comment]
比如山海逆战 或者新著龙虎门， 很多港漫他们比较多更新 感激

**Comment by sango2001** [comment]
https://www.setnmh.com/ 和tvbsmh.com 好像都出自同一個資源，具體不知道哪個好，但是我平時去tvbsmh.com 最新的會延續一周才可以觀看，否則不許vip 看，麻煩大大幫忙，感激

**Comment by sango2001** [comment]
想问一下是否在测试支持这个网站啊，一直没看到回复，不知道是否在忙？
