### ISSUE TITLE
有些網址一加入就當掉

### ISSUE THREAD

**Issue by LH1331** [eight04/ComicCrawler#267]
如題，有些網址一加入分析就當掉

比如PIXIV的：
https://www.pixiv.net/users/7204795
或者漫畫櫃的：
https://tw.manhuagui.com/comic/24591/

可能是名稱有特殊符號的關係吧
像「...」或「、」好像都不行

**Comment by eight04** [comment]
「就當掉」是指什麼？是指整個電腦藍屏？還是有什麼錯誤訊息？

**Comment by LH1331** [comment]
command line裡面最後一行跑到「analyzing success！」
但是gui沒有回應，當掉的是gui，必須強制關閉，session也會遺失

漫畫櫃的那個連結今天再次嘗試，可以成功下載了
PIXIV的那個情況依舊

**Comment by eight04** [comment]
我這邊測試兩個網址都能正常跳出選擇集數的視窗。Windows 10 + Python 3.8.1

有沒有可能視窗有跳出來但因為某種原因沒有顯示？例如跑到桌面之外

**Comment by LH1331** [comment]
我使用的是win7+3.8.5，我確定視窗沒有跑到桌面外

試了兩個月，我想有可能是寫入win7檔案名稱時出現保留字元的緣故
這位作者的圖檔名稱有出現?跟:

**Comment by eight04** [comment]
你有試過 CLI 模式嗎？
```
comiccrawler download https://tw.manhuagui.com/comic/24591/
```

**Comment by LH1331** [comment]
成功下載了，謝謝你!

檔名被替換成了大寫
這是甚麼神奇的魔術？：D

**Comment by eight04** [comment]
這樣看來，我認為是電腦上的 Tkinter 有問題，以至於無法顯示選擇集數的對話框。你可以試試

1. 重新安裝 python
2. 如果知道語法的話，可以在這附近
    https://github.com/eight04/ComicCrawler/blob/f87b34d22174dbf960be93ee87e325c0a9a673c1/comiccrawler/gui/select_episodes.py#L22
    建立一個 breakpoint，然後逐步執行看是在哪一行卡住的。


> 檔名被替換成了大寫

ComicCrawler 在存檔時會把一些非法的字元替替換成 unicode︰

https://github.com/eight04/ComicCrawler/blob/f87b34d22174dbf960be93ee87e325c0a9a673c1/comiccrawler/util.py#L9-L28
