### ISSUE TITLE
感激添加了setnmh 在mods 里， 但麻烦告诉我如何增加在gui 的页面里

### ISSUE THREAD

**Issue by sango2001** [eight04/ComicCrawler#276]
首先非常感激大大抽空帮忙增加了setnmh 网站的支持，但是我属于小白，想再次问一下当我运行 comiccrawler gui 以后， 在支持的网域里没有看到setnmh 网站， 可是在mods 里我明确看到了这网站的档案。 能简单教一下我如何把这setnmh mods 在gui 里支持吗？ 万分感激

**Comment by eight04** [comment]
> 在mods 里我明确看到了这网站的档案

你這裡寫的 "mods" 指的是電腦裡的資料夾嗎？還是？

**Comment by sango2001** [comment]
再次谢谢回复，我很笨，今天花了很多时间终于搞定，我把整个档案解压到C 盘， 然后直接下载新的覆盖在C 盘里，原来所有的档案都在 c:/python38/lib/comicrawler 里， 所以变成里面的档案没更新过，导致一直出错，找了好久终于搞定。再次谢谢你百忙抽空更新，感激了，问题已经解决。
