### ISSUE TITLE
cartoonmad 下載失敗

### ISSUE THREAD

**Issue by rickchen16** [eight04/ComicCrawler#278]
mh_info裡面沒有totalimg這個欄位
所以拿不到這一話有多少頁
嘗試用很醜的方式修了一下(仿照網站本身拿totalImageCount的方式)
看來可以work
另外cartoonmad下載也失敗了
感覺是直接accessa漫畫內頁(ex:https://www.cartoonmad.cc/comic/749100012025001.html)
會看到訊息"頁面閒置過久或入徑錯誤，請回作品頁面從新進入 , TKS !"
而看不到圖片導致的
試了一下
refer帶https://www.cartoonmad.com/
應該就可以拿到完整網頁內容
另外img src有變
這是現在的 img src="https://www.cartoonmad.com/comic/comicpic.asp?file=/7491/001/001"
所以re的參數應該也要動了

下載的漫畫url:
https://www.ohmanhua.com/15335/
https://www.cartoonmad.com/comic/7491.html

`__Ox97c0e = re.search("var __Ox97c0e=\[[^]]+]", str(scripts)).group(0)`
`if(typeof mh_info[__Ox97c0e[0x0]]==__Ox97c0e[0x1]){totalImageCount=mh_info[__Ox97c0e[0x2]]}else{totalImageCount=parseInt(eval(base64[__Ox97c0e[0x4]](__Ox97c0e[0x3])))}`

**Comment by eight04** [comment]
下次不同的網站不同問題請分別開一個issue，我先把這轉成 cartoonmad，oh 漫畫移至 #280
