### ISSUE TITLE
關於e紳士的問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#29]
下載一切都ok，不過有的漫畫圖片原來size比較
大被自動縮了，抓下來也是被縮過的圖片，下載
的時候有辦法選擇或是自動抓original size的嗎

像下面這本
https://exhentai.org/g/8082/a27ae27be4/
第一張本來是1576x1280看的時候被縮成1280x1040
抓下來也是後頭被縮過的圖片大小。

**Comment by eight04** [comment]
在設定檔 setting.ini 中可以調整
```
[e紳士]
original = true
```

**Comment by kesdoputr** [comment]
喔喔原來可以設定，眼殘了感謝回答m(_ _)m

**Comment by kesdoputr** [comment]
不好意思，我剛去把設定改為true以後抓下來的還是
小張的圖，我看e紳士的設定底下只有三個
cookie_ipb_pass_hash
cookie_ipb_member_id
original

版本已經更新到12.20

**Comment by eight04** [comment]
已於 2017.1.3 修正
