### ISSUE TITLE
cocomanhua 下載失敗

### ISSUE THREAD

**Issue by rickchen16** [eight04/ComicCrawler#294]
https://www.cocomanhua.com/15335/
下載會出現
node_vm2.VMError: setInterval is not defined
這個錯誤

**Comment by rickchen16** [comment]
研究了一下
有2個錯誤
1. node_vm2不能用setInterval 這類的scheduling functions
    oh.py的javascript補了一行const setInterval = console.log;看來可以避開
2.  接著會撞到node_vm2.VMError: window[__Oxb02b6[28]] is not a function
    window[__Oxb02b6[28]]對應的值為addEventListener
    對應的javascript應該是
    window[__Oxb02b6[0x1c]](__Oxb02b6[0x1a], (_0xb51bx13)=>{
        if (_0xb51bx13[__Oxb02b6[0x1b]][__Oxb02b6[0x18]]) {
            devmodedetect()
        }
    }
    );
    不知道為什麼不能用，猜測是因為const window = global;後的關係
    看了一下這個應該是處理鍵盤和滑鼠事件，下載漫畫應該不需要
    直接取代掉
    oh.py裡改為str(scripts).replace('window[__Oxb02b6[0x1c]]', 'console.log')

以上2個patch後可以下載囉

**Comment by eight04** [comment]
Move to #306
