### ISSUE TITLE
DMZJ被隱藏的漫畫有辦法下載嗎？

### ISSUE THREAD

**Issue by kof11** [eight04/ComicCrawler#303]
舉例來說這個
https://manhua.dmzj.com/zhandoupohuaixueyuandangerous/
表面上看似被刪除了，但實際上GOOGLE還是搜尋得到話數
https://manhua.dmzj.com/zhandoupohuaixueyuandangerous/57753.shtml
貼到下載器會顯示
https://i.imgur.com/TIs8Udv.jpg

**Comment by kof11** [comment]
自己找到了答案，在Tachiyomi這個APP上可以下載DMZJ被隱藏的漫畫，雖然有點麻煩，但也只能這樣了，
我為何要問這個問題呢？因為我發現還真有漫畫是在DMZJ被隱藏的漫畫裡才收錄完全的，其他漫畫網全都收錄殘缺，盜版網站連爬蟲都爬不徹底，呵呵。

**Comment by eight04** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5624

**Comment by eight04** [comment]
卡卡的，連不進
