### ISSUE TITLE
ikanman 會下載到 .webp

### ISSUE THREAD

**Issue by yoxahu** [eight04/ComicCrawler#31]
不確定是否每部漫畫皆如此，某些漫畫
用 Chrome 瀏覽會得到 .webp 或 .jpg.webp 或 .png.webp (本質上仍是.webp)
用 Firefox 瀏覽會得到 .jpg 或 .png
用最新版 ComicCrawler 只會得到 .webp (以前舊版抓到的是 .jpg 或 .png)

.webp 的壓縮比雖遠高於 .jpg/.png
但若 ikanman 是以原本的 .jpg/.png 再次壓縮為 .webp，畫質必然損失
一些比較不講究畫工的漫畫用 .webp 來節省容量倒是不錯的選擇
不過目前許多漫畫瀏覽或看圖軟體、APP 尚未支援 .webp

因此希望 ComicCrawler 能在 setting.ini 裡設定要不要接受 .webp

**Comment by eight04** [comment]
👍 我沒注意過是否 ikanman 的 webp 是從 jpg 轉來的，但還滿多人希望不要用 webp 的。

**Comment by eight04** [comment]
Fixed in 2017.1.10.

**Comment by yoxahu** [comment]
感謝埃特四號迅速解決這個問題！

以後說不定會出現擋 WebP 的 Extensions~
