### ISSUE TITLE
除了 圖書館 之外，還需要另一個 追蹤進度機制

### ISSUE THREAD

**Issue by yoxahu** [eight04/ComicCrawler#32]
有些漫畫會想下載保存，有些只會跟連載看看打發時間，兩個機制不宜混在一起
所以會有類似「漫畫書籤」的需求

就是對於「加入書籤」的漫畫網址，可以由使用者標記閱讀進度到哪一話
而按下「檢查更新」後，Gui 欄位會提示目前已有新連載還沒追
點擊漫畫名稱則打開瀏覽器至目標頁面

加入這個特色，讓 ComicCrawler 除了是扒漫畫神器，也是追漫畫神器！！！

（還有更激進的想法，搭配另一個專案 comic-viewer，直接解析要閱讀的那一話餵給瀏覽器）
（搭配 comic-viewer 這個想著爽就好，沒有吃飽不需要去實作 XD）

**Comment by eight04** [comment]
幫你整理一下︰

1. 使用者可以把網址加入書籤並標記某一話
2. 按下書籤可以開啟該網址
3. 檢查各書籤是否有新進度
4. 不用下載圖片

Comic Crawler 的主要功能就是下載圖片，和 4. 違背。至於 1.~3.，大部份的線上漫畫網站都有這功能了，我認為自己去扒每個網址再分析是否有更新，還不如註冊個帳號，登入時網站自動提醒你。

**Comment by yoxahu** [comment]
整理的沒錯，條理清晰給推！

註冊帳號沒辦法一次掃描不同漫畫站台，多站台須要多註冊、多登入…
而且不同站台對於同一部漫畫的更新速度有快有慢…

我理解 Comic Crawler 主旨就是下載
但若附加這個功能不需要添加太多程式碼就可以達成
請考慮高抬貴手

**Comment by eight04** [comment]
Comic Crawler 的確可以分析 chapter，但書籤是完全沒有的。存檔只會記住已下載的 chapter，檢查更新也只是檢查是否有集數未下載完成而已（你可以嘗試加入一個任務後不下載，而是檢查更新。檢查後它的狀態會顯示為「有更新」）。

再來，Comic Crawler 所支援的網站有限，目前的支援列表是以下載為主，只有獨佔或高解析度的網站才會支援。若是加入這個功能勢必會變成以大眾使用的網站為主，這會大量加長支援的清單，也是我不願見到的。

即使我想做這種功能，我也不會把它加入 Comic Crawler 內。做成瀏覽器的附加元件顯然是一個比較好的選項。

**Comment by yoxahu** [comment]
我是希望針對一個漫畫網址，可以給他一個數字（直接輸入或經由選取），代表我閱讀到哪理
而藉由 Comic Crawler 獲得的最新 chapter 數字，與我設定的數字比較，如果不一致就顯示提醒

本來以為「書籤」和「圖書館」的差異只在於「是否進行下載動作」以及「多輸入一組數字來比較」

所請求的「書籤標示」只是一個漫畫網址對應一個數字 【已閱讀到第87話】：【已更新到94話】
並非針對每一個漫畫網址包含的所有話數都作紀錄標示；「按下書籤」也不是要打開標示閱讀進度的那一話，是打開那部漫畫的目錄頁（就是和下載漫畫輸入一樣的網址）

沒想到實作上會有這麼多問題需要考慮，果然會不會寫程式是兩種腦袋@@"

我是不覺得會存在什麼「面向大眾使用的網站為主」的問題，目前支援的網站就已經夠豐富與符合需求
另一方面，這屬於對既存功能的延伸輔助，本來就只需要支援原本可以分析下載的目標網域而已

**Comment by eight04** [comment]
這是不可能的，因為漫畫標題並不是只有話數。#30 有些範例可以看。

**Comment by yoxahu** [comment]
糟糕！是我看的漫畫太少！仔細回想的確有些漫畫是以章節形式發布的~_~
