### ISSUE TITLE
漫畫櫃 manhuagui 網站和 山立網站下載都出現問題

### ISSUE THREAD

**Issue by sango2001** [eight04/ComicCrawler#320]
嘗試下載 山海逆戰， 上周還可以，這周就出現 line 338, in error_loop, line 289 line 51, line 58, line 186, line 95

![comic](https://user-images.githubusercontent.com/67833453/145672612-820312f7-d499-4f58-add2-086bd579d875.jpg)
已經發圖， 蠻煩修復，感激， 謝謝
p

**Comment by sango2001** [comment]
直接登錄網站是可以看到漫畫的，所以不是網站問題，可能他們修改了部分位置，具體我不清楚， 謝謝

**Comment by rickchen16** [comment]
manhuagui 網站網站確認了一下
html網頁改了
以前可能是src="https://cf.hamreus.com/scripts/config_5F5A8A8B46A7B711EC3579AFD755010FA8E85725.js"

現在是src="//cf.hamreus.com/scripts/config_5F5A8A8B46A7B711EC3579AFD755010FA8E85725.js"
前面的https:沒有了
所以會有錯
按下方式修改可以先避開這個問題
comiccrawler\mods\seemh.py
	# configjs_url = re.search(
	configjs_url = 'https:' + re.search(
		# r'src="(https?://[^"]+?/config_\w+?\.js)"',
		r'src="(//[^"]+?/config_\w+?\.js)"',
		html
	).group(1)

       # corejs_url = re.search(
	corejs_url = 'https:' + re.search(
		# r'src="(https?://[^"]+?/core_\w+?\.js)"',
		r'src="(//[^"]+?/core_\w+?\.js)"',
		html
	).group(1)

**Comment by sango2001** [comment]
麻煩能改一下這個檔案讓我下載嗎？我手動修改了，結果報錯。 連comiccrawler 都打不開
![524](https://user-images.githubusercontent.com/67833453/145737212-a4f4da64-e6df-44b8-a780-c067c62e6e83.jpg)
。

**Comment by rickchen16** [comment]
> 麻煩能改一下這個檔案讓我下載嗎？我手動修改了，結果報錯。 連comiccrawler 都打不開 ![524](https://user-images.githubusercontent.com/67833453/145737212-a4f4da64-e6df-44b8-a780-c067c62e6e83.jpg) 。

放了[se](https://github.com/eight04/ComicCrawler/files/7700312/seemh.zip)
你的感覺檔案編碼被改壞了

**Comment by sango2001** [comment]
thx it work now, cheer

**Comment by eight04** [comment]
等這個 repo 也修好再關這個 issue，或是 @rickchen16 也可以發個 PR

**Comment by sango2001** [comment]
雖然你更新了，我還是不懂如何更新，嘗試整個下載或者update 也無法更新，麻煩告知正確更新方法，謝謝
就是如何下載comiccrawler 取代舊檔。

**Comment by eight04** [comment]
Python 程式的開發留程是這樣︰

1. 寫 code，傳到 Github 上，可以測試、討論、檢查錯誤、etc。
2. 一切正常後，tag 一個新的版本數字。
3. 把這些 code 打包/壓縮成一個 package，並且把這個 package 上傳到 pypi.org。

#323 只做了 (1) 的部份，所以你不會在 pypi.org 裡找到新版本的 comiccrawler。

如果想要測試最新的、還沒打包成 package 的程式碼，得從 Github 下載最新的程式碼︰

1. 安裝 [git](https://git-scm.com/)
2. 安裝 [python](https://www.python.org/downloads/)
3. 安裝 [vpip](https://pypi.org/project/vpip/)，一個用來管理 python package 的工具。執行 `pip install vpip`
4. 接下來就可以在命令行完成了︰
    ```cmd
    git clone https://github.com/eight04/ComicCrawler.git
    cd ComicCrawler
    vpip install
    vpip link
    ```
`vpip link` 後，你的 comiccrawler 指令「應該」就會使用最新的程式碼了。未來如果要更新，就直接在 ComicCrawler 資料夾底下執行 `git pull`，git 就會幫你把最新的程式碼下載下來。

**Comment by eight04** [comment]
我看不到你的圖。如果你是直接在 email 中插入圖片，那我猜 notifications@github.com 可能不會把附加的圖片自動上傳到 Github，而是捨棄。

**Comment by sango2001** [comment]
![圖一](https://user-images.githubusercontent.com/67833453/150434117-325b6f31-ffb7-4b2e-b0d4-5c4f3f7a7ec0.jpg)
![圖2](https://user-images.githubusercontent.com/67833453/150434130-0a747676-1ec3-432d-a934-2d722b075281.jpg)
![圖4](https://user-images.githubusercontent.com/67833453/150434147-ad1d386e-b927-4e1c-8397-0cc7e9134719.jpg)

**Comment by sango2001** [comment]
抱歉我用email 直接回復，可能沒有上傳圖片，這是之前的圖，麻煩看看

**Comment by eight04** [comment]
看起來是 setuptools 的版本太老了，跟 python 3.10 衝突。

1. 把 `.venv` 資料夾刪除，
2. 編輯 `requirements-lock.txt`，把 `setuptools==41.2.0` 這行刪除，存檔。
3. 重行執行 `vpip install`。

**Comment by sango2001** [comment]
想問一下 git clone http://github.com/eight04/ComicCrawler.git 在那個目錄裏執行
比如我安裝python 在
C:\Users\NewWorld\AppData\Local\Programs\Python\Python310\Lib\site-packages
我應該在這裏執行，還是在 c:\ 執行

[https://opengraph.githubassets.com/29cdba0d21e13fb4b7d6b0625964bd62813157671a8a7eb6317ca02b8033231b/eight04/ComicCrawler]<http://github.com/eight04/ComicCrawler.git>
GitHub - eight04/ComicCrawler: An image crawler written in Python.<http://github.com/eight04/ComicCrawler.git>
An image crawler written in Python. Contribute to eight04/ComicCrawler development by creating an account on GitHub.
github.com


________________________________

**Comment by eight04** [comment]
沒有一定。以我自身為例，會把專案統一放在 `D:\dev` 資料夾內，那麼我在 `D:\dev` 裡執行 `git clone http://github.com/eight04/ComicCrawler.git`，git 就會把程式碼下載進 `D:\dev\ComicCrawer` 資料夾。

**Comment by sango2001** [comment]
那如何运行呢， 还是comiccrawler gui 吗， 但是他会在python 的 site packages 那里运行。 我按你方法做完， 然后怎么把他搬到或者复制回python 里

**Comment by eight04** [comment]
你現在有兩個 python 環境，一個是外面的 `C:\Users\NewWorld\AppData\Local\Programs\Python\Python310`，一個是專案內 `.venv` 資料夾底下的。

若要執行專案內的，你可以

* 在 ComicCrawler 資料夾底下執行 `vpip run comiccrawler gui`。或是
* 直接執行 `"D:\dev\ComicCrawler\.venv\Scripts\comiccrawler.exe" gui`。也可以
* 執行 `vpip link` 指令，vpip 會把專案內的 `comiccrawler.exe` 連到外面 python 的 Scripts 資料夾，以後就可以直接打 `comiccrawler gui`，不需要加一長串資料夾。

另外，外面的 python 中還是安裝著 comiccrawler，可以執行 `pip uninstall comiccrawler` 解除安裝。不用擔心，它不會影響專案內的。

**Comment by sango2001** [comment]
在comiccraweler 運行 vpip run comiccrawler gui 很正常， 
但如果在 c:\comiccrawler\ vpip link
執行完
在普通時候打comiccrawler gui 說找不到 紅色字
![01](https://user-images.githubusercontent.com/67833453/150516685-aa7e72f6-f7ad-4253-bc46-9d61db40dc2d.jpg)

**Comment by eight04** [comment]
你沒做錯，是 `vpip link` 壞了︰https://github.com/eight04/vpip/issues/36

**Comment by sango2001** [comment]
今天看到你有新的更新，所以就按照你之前的更新了，可是下載的時候出現了這個問題
![Untitled](https://user-images.githubusercontent.com/67833453/152509870-650842e8-021f-43c4-8e8e-a078c9469c27.jpg)

**Comment by eight04** [comment]
不同的問題請開一個新的 issue
