### ISSUE TITLE
拷贝漫画更改了域名导致变成“不支持的网址”

### ISSUE THREAD

**Issue by yhxkry** [eight04/ComicCrawler#327]
拷贝漫画现在域名改成了 copymanga.org而不是原来的copymanga.com，请问大佬这个怎么处理？

**Comment by eight04** [comment]
域名的設定在這︰
https://github.com/eight04/ComicCrawler/blob/56cee52e4e1c2eeb86433743182231626ce8c6fc/comiccrawler/mods/copy.py#L18
可以改成
```py
["copymanga.com", "copymanga.org"]
```
----
不過我可以正常點進 copymanga.com 就是了。

**Comment by yhxkry** [comment]
> 域名的設定在這︰
> 
> https://github.com/eight04/ComicCrawler/blob/56cee52e4e1c2eeb86433743182231626ce8c6fc/comiccrawler/mods/copy.py#L18
> 
> 
> 可以改成
> ```python
> ["copymanga.com", "copymanga.org"]
> ```
> 
> 不過我可以正常點進 copymanga.com 就是了。

谢谢~学到了，解决了。 拷贝被恶意攻击域名解析不稳定，有些地方可能能上去.com吧，我这边都不行。
