### ISSUE TITLE
山立網站下載不了漫畫，麻煩修改一下，感激

### ISSUE THREAD

**Issue by sango2001** [eight04/ComicCrawler#329]
山立網站下載不了漫畫，麻煩修改一下，感激
![001](https://user-images.githubusercontent.com/67833453/155843442-5ced1d1c-d71a-4857-958a-6e2f267b92f2.jpg)

**Comment by eight04** [comment]
這應該是山立網站的問題，建議回報給山立。

它標題寫有46P，但網頁實際上有47頁，而且第47頁沒圖。

**Comment by sango2001** [comment]
好的，謝謝，我想山立也不會理會我們，他只是個網站給你看漫畫，應該不會改動的
