### ISSUE TITLE
一些小問題

### ISSUE THREAD

**Issue by kof11** [eight04/ComicCrawler#33]
布卡漫画有些作品解析後顯示的不是話數，而是各話標題，可否一律為話數?
如:http://www.buka.cn/detail/217804

dmzj的網站，www.開頭的網頁無法解析，但把www.換成m.之後又可以解析了
如:http://www.dmzj.com/info/xixingji.html

**Comment by eight04** [comment]
dmzj 有三個網域呢…

* manhua.dmzj.com - 日漫
* www.dmzj.com - 原創
* m.dmzj.com - 手機版

日漫和原創互不相通，但日漫和原創都可以在手機版裡找到。

**Comment by eight04** [comment]
於 2017.2.5 修正
