### ISSUE TITLE
[FR] Switch to cookies.txt, clear cookies after expired

### ISSUE THREAD

**Issue by LH1331** [eight04/ComicCrawler#330]
將setting.ini中的cookie_PHPSESSID更新後就正常了
希望以後的版本能添加cookies過期的提示，謝謝

**Comment by eight04** [comment]
目前 ComicCrawler 沒有記錄 cookie 的有效期限。未來會漸漸轉用 curl 指令，其中也不會記錄 cookie 的有效期限。

要記錄有效期限，可能要使用更複雜的 cookies.txt，配合瀏覽器的附加元件。

另外注意︰就算 cookie 沒過期，也是可能遇到這類 HTTP 錯誤。唯一可以避免這個錯誤的方法是，請對方把伺服器程式寫好，並且回傳有用的錯誤訊息。
