### ISSUE TITLE
抓無限的漫畫出現的奇怪問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#334]
剛剛抓王者天下，顯示有734更新，下載後發現只有第一張是對的，後頭的頁數程式
跑去抓了單行本第一卷
https://www.comicabc.com/ReadComic/6997/734/734_8d00xI27S.html

試了同樣無限的咒術迴戰最新一回就正常下載

另外可否加入www.comicabc.com的域名支持？目前手動改成之前用的comicbus能添加，用comicabc不行

感謝您的回答m(_ _)m

**Comment by kesdoputr** [comment]
轉生史萊姆也發生一樣的狀況，只有第一張是對的後頭都是第一回
https://www.comicabc.com/ReadComic/13313/100/100832Y471a_7.html

**Comment by frankieyen** [comment]
別的漫畫好像也有遇過類似狀況
