### ISSUE TITLE
e紳士解析錯誤問題

### ISSUE THREAD

**Issue by Link-KS** [eight04/ComicCrawler#34]
我在mods\exh.py中輸入了自己的cookie_ipb_member_id、cookie_ipb_pass_hash之後嘗試扒一個e紳士的圖，但是輸入連接后提示「解析錯誤！list index out of range」。關閉gui后發現console提示以下錯誤信息：

IndexError: list index out of range
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\comiccrawler\core\__init__.py", line 571, in analyze
    analyze_info(mission, mission.module)
  File "c:\program files\anaconda3\lib\site-packages\comiccrawler\core\__init__.py", line 633, in analyze_info
    mission.title = mod.get_title(html, mission.url)
  File "c:\program files\anaconda3\lib\site-packages\comiccrawler\mods\exh.py", line 33, in get_title
    t = t[-1][1]

請問我是不是有什麽地方沒有設置正確呢？順便一提，我扒的是這個：https://exhentai.org/g/1025661/014c7c2f0e/

**Comment by eight04** [comment]
不要修改原始碼，程式會從設定檔中讀取 cookie 資訊。
https://github.com/eight04/ComicCrawler#%E8%A8%AD%E5%AE%9A%E6%AA%94

至於你改的東西叫「預設值」，如果設定檔不存在才會使用預設值。

**Comment by starobots** [comment]
原来的变量叫做ipb_member_id和ipb_pass_hash，
然后现在的变量叫做cookie_ipb_member_id和cookie_ipb_pass_hash。
去年12月更新了一次，这次更新了2月5号版本，对比了一下发现设定里面的变量变了，要重新填一下。
还有original是什么意思？

**Comment by eight04** [comment]
關於設定檔 Cookie 的改動請參考︰https://github.com/eight04/ComicCrawler#20161220-%E6%9B%B4%E6%96%B0

Ex 設定中的 original 若是設為 True，會下載原圖；設為 False，則是下載縮圖。縮圖就是一般瀏覽網頁時你看到的圖片，寬度一般不會超過 1280px；原圖則是最下方的 "Download Original Source" 選項。但是下載原圖時所消耗的 Image Limits 是縮圖的 5 倍。
