### ISSUE TITLE
deno訊息

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#372]
近期在下載漫畫時，會跳出關於deno的訊息。圖片目前仍能下載。
麻煩eight04大大幫忙瞭解一下，謝謝。

範例網址：
https://www.dm5.com/manhua-shuangxingzhiyinyangshi/

log:
 The `Worker.deno.permissions` API was used with `--unstable` flag. The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-worker-options` instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags

**Comment by eight04** [comment]
簡單的說，deno 有個參數在 2.0 版本以後會無效，也就是這裡要早點改掉︰
https://github.com/eight04/deno_vm/blob/ec59fc8f97a80b167af1857adcd9fc99e5aa19b2/deno_vm/__init__.py#L242

在你的 deno 升到2.0版本前應該是不影響運作。

**Comment by Zivch** [comment]
所以建議的策略就是不要升級deno嗎？
好的，謝謝。

**Comment by eight04** [comment]
Fixed in #373
