### ISSUE TITLE
pixiv無法下載

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#394]
網址能加入任務列表，也能讀取到集數，但是無法下載
以下是命令提示字元的訊息

> Microsoft Windows [版本 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> C:\Users\Argon>comiccrawler gui
> Session saved
> Start analyzing https://www.pixiv.net/member_illust.php?id=95588312
> Analyzing https://www.pixiv.net/ajax/user/95588312/profile/illusts?ids%5B%5D=124
> 750727&ids%5B%5D=124589567&ids%5B%5D=124514273&ids%5B%5D=124457901&ids%5B%5D=124
> 243878&ids%5B%5D=123921117&ids%5B%5D=123802758&ids%5B%5D=123725777&ids%5B%5D=123
> 725354&ids%5B%5D=123588326&ids%5B%5D=123519134&ids%5B%5D=123367502&ids%5B%5D=123
> 343916&ids%5B%5D=123215721&ids%5B%5D=123189556&ids%5B%5D=123189436&ids%5B%5D=123
> 063889&ids%5B%5D=122925693&ids%5B%5D=122859376&ids%5B%5D=122773334&ids%5B%5D=122
> 684356&ids%5B%5D=122647971&ids%5B%5D=122647251&ids%5B%5D=122632257&ids%5B%5D=122
> 590656&ids%5B%5D=122586132&ids%5B%5D=122562678&ids%5B%5D=122471043&ids%5B%5D=122
> 374879&ids%5B%5D=122332626&ids%5B%5D=122331700&ids%5B%5D=122230151&ids%5B%5D=122
> 171086&ids%5B%5D=122138040&ids%5B%5D=122034216&ids%5B%5D=122023951&ids%5B%5D=121
> 996406&ids%5B%5D=121920603&ids%5B%5D=121892986&ids%5B%5D=121863803&ids%5B%5D=121
> 774704&ids%5B%5D=121774517&ids%5B%5D=121683124&ids%5B%5D=121651825&ids%5B%5D=121
> 651512&ids%5B%5D=121498814&ids%5B%5D=121498625&ids%5B%5D=121401387&is_manga_top=
> 0&work_category=illustManga&is_first_page=1...
> Analyzing https://www.pixiv.net/ajax/user/95588312/profile/illusts?ids%5B%5D=121
> 399598&ids%5B%5D=121272980&ids%5B%5D=121250410&ids%5B%5D=121240340&ids%5B%5D=121
> 220965&ids%5B%5D=121173728&ids%5B%5D=121147005&ids%5B%5D=121063420&ids%5B%5D=121
> 003898&ids%5B%5D=120957128&ids%5B%5D=120940109&ids%5B%5D=120885572&ids%5B%5D=120
> 885172&ids%5B%5D=120855053&ids%5B%5D=120853694&ids%5B%5D=120787080&ids%5B%5D=120
> 785645&ids%5B%5D=120627276&ids%5B%5D=120539231&ids%5B%5D=120507481&ids%5B%5D=120
> 394808&ids%5B%5D=120328119&ids%5B%5D=120327157&ids%5B%5D=120323776&ids%5B%5D=120
> 218686&ids%5B%5D=120218569&ids%5B%5D=120218479&ids%5B%5D=120132625&ids%5B%5D=120
> 119132&ids%5B%5D=120061693&ids%5B%5D=120057065&ids%5B%5D=120056599&ids%5B%5D=120
> 056217&ids%5B%5D=120055303&ids%5B%5D=119999247&ids%5B%5D=119907366&ids%5B%5D=119
> 903592&ids%5B%5D=119762278&ids%5B%5D=119733674&ids%5B%5D=119641797&ids%5B%5D=119
> 639746&ids%5B%5D=119532456&ids%5B%5D=119531729&ids%5B%5D=119391378&ids%5B%5D=119
> 390518&ids%5B%5D=119280203&ids%5B%5D=119188120&ids%5B%5D=119114335&is_manga_top=
> 0&work_category=illustManga&is_first_page=0...
> Analyzing https://www.pixiv.net/ajax/user/95588312/profile/illusts?ids%5B%5D=119
> 074334&ids%5B%5D=119040397&ids%5B%5D=119016032&ids%5B%5D=118978217&ids%5B%5D=118
> 879678&ids%5B%5D=118762489&ids%5B%5D=118757915&ids%5B%5D=118749337&ids%5B%5D=118
> 709868&ids%5B%5D=118671066&ids%5B%5D=118641831&ids%5B%5D=118635621&ids%5B%5D=118
> 588056&ids%5B%5D=118558528&ids%5B%5D=118500877&ids%5B%5D=118467101&ids%5B%5D=118
> 438159&ids%5B%5D=118436311&ids%5B%5D=118336830&ids%5B%5D=118312738&ids%5B%5D=118
> 241989&ids%5B%5D=118241855&ids%5B%5D=118212762&ids%5B%5D=118142868&ids%5B%5D=118
> 134947&ids%5B%5D=118130658&ids%5B%5D=118116314&ids%5B%5D=118107910&ids%5B%5D=118
> 107416&ids%5B%5D=118061371&ids%5B%5D=118048921&ids%5B%5D=118036074&ids%5B%5D=118
> 035940&ids%5B%5D=118035871&ids%5B%5D=118022301&ids%5B%5D=118003358&ids%5B%5D=118
> 003240&ids%5B%5D=117983472&ids%5B%5D=117942959&ids%5B%5D=117844539&ids%5B%5D=117
> 731583&ids%5B%5D=117675373&ids%5B%5D=117646613&ids%5B%5D=117553245&ids%5B%5D=117
> 504932&ids%5B%5D=117465255&ids%5B%5D=116360615&ids%5B%5D=116063888&is_manga_top=
> 0&work_category=illustManga&is_first_page=0...
> Analyzing success!
> Start download 95588312 - agargreen
> Start downloading 95588312 - agargreen
> total 144 episode.
> Downloading ep 116063888 - プリズマ バレンタイン
> Traceback (most recent call last):
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 338, in error_loop
>     process()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 289, in download
>     crawler.init()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 51, in init
>     self.init_images(self.ep.current_page - 1)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 57, in init_images
>     self.get_html()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 177, in get_html
>     self.html = self.downloader.html(self.ep.current_url)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\module_grabber.py", line 11, in html
>     return self.grab(grabhtml, url, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\module_grabber.py", line 24, in grab
>     **kwargs
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 151, in grabhtml
>     r = grabber(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 105, in grabber
>     r = await_(do_request, s, url, proxies, retry, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 905, in wrapped
>     return f(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 927, in await_
>     return async_(callback, *args, **kwargs).get()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 682, in get
>     raise err
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 474, in wrap_worker
>     self.ret = self.worker(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 131, in do_request
>     r.raise_for_status()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\requests\models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.
> pixiv.net/artworks/116063888
> Traceback (most recent call last):
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 338, in error_loop
>     process()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 289, in download
>     crawler.init()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 51, in init
>     self.init_images(self.ep.current_page - 1)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 57, in init_images
>     self.get_html()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\crawler.py", line 177, in get_html
>     self.html = self.downloader.html(self.ep.current_url)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\module_grabber.py", line 11, in html
>     return self.grab(grabhtml, url, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\module_grabber.py", line 24, in grab
>     **kwargs
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 151, in grabhtml
>     r = grabber(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 105, in grabber
>     r = await_(do_request, s, url, proxies, retry, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 905, in wrapped
>     return f(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 927, in await_
>     return async_(callback, *args, **kwargs).get()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 682, in get
>     raise err
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\worker\__init__.py", line 474, in wrap_worker
>     self.ret = self.worker(*args, **kwargs)
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\comiccrawler\grabber.py", line 131, in do_request
>     r.raise_for_status()
>   File "c:\users\argon\appdata\local\programs\python\python36-32\lib\site-packag
> es\requests\models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.
> pixiv.net/artworks/116063888
> Stop downloading
> 停止下載
>

**Comment by eight04** [comment]
這應該也是被 cloudflare 擋掉了。已於 #393 修正。我等等釋出一個新版本

**Comment by eight04** [comment]
Fixed in 2024.12.6
