### ISSUE TITLE
pip update / upgrade

### ISSUE THREAD

**Issue by j129008** [eight04/ComicCrawler#4]
![image](https://cloud.githubusercontent.com/assets/3248873/8548264/6488e300-24f6-11e5-8d8a-ba915e2128ab.png)

說明檔案寫的更新方法是:
pip install --update comiccrawler

不過我這樣沒辦法更新, 只好用
pip install comiccrawler --upgrade

是不是只有我這樣@@

**Comment by eight04** [comment]
你是正確的，應該是 --upgrade 才對。等等我來改 readme。
