### ISSUE TITLE
執行 2017.3.25 版本會出現錯誤

### ISSUE THREAD

**Issue by danny0838** [eight04/ComicCrawler#42]
執行 `comiccrawler gui` 時，會發生 `ModuleNotFoundError: No module named 'execjs'` 錯誤而中止整個程式

把 manhuadao.py 刪除即正常，看起來是 manhuadao.py 模組使用了 execjs 導致

**Comment by eight04** [comment]
我在 build 的時候沒把舊檔案刪除，結果 python wheel 裡還留有舊檔案 😱

**Comment by eight04** [comment]
Fixed in 2017.3.26
