### ISSUE TITLE
在章節名稱加上流水號

### ISSUE THREAD

**Issue by wby238** [eight04/ComicCrawler#43]
原始章節名指的是網頁原本的順序，例如，原始章節名爲：
```
番外1
第1話
番外2
第2話
第3話
```
保存的章節名爲：
```
0001 番外1
0002 第1話
0003 番外2
0004 第2話
0005 第3話
```

**Comment by eight04** [comment]
是指「依章節順序在原始名稱之前加上流水號」？目前沒辦法。你可以用重命名程式，把章節資料夾按建立日期排序後，再加入流水號。

為什麼你會想這麼做？

**Comment by wby238** [comment]
@eight04 
對的，但準確來說可以是按網頁的建立順序排列。

如果是按建立日期排序的話，很多資料夾的建立日期都是相同的。這樣就沒辦法排序了。

至於想這樣做的原因，最主要是為了讓其他看漫畫軟體(例如mangameeya)方便讀取以免讀錯順序，其次是防止中文數字導致的排序錯亂。

**Comment by eight04** [comment]
資料夾的建立日期不會是相同的，除非你開兩個程式同時抓同一份漫畫。

章節的排列順序也**不是**按照網頁的建立順序排序，而是按漫畫網站上給出的順序。若網站把番外排在一起，扒下來時番外也會排在一起。

承上，網站本身也不一定按推出時間排序，缺集數、未漢化、一次更新多集、先出連載再出單行本等等情況都有。

Comic Crawler 沒有能力得知每章推出的時間，它只知道網頁長什麼樣子，和之前的紀錄相比是否有章節被增加/移除而已。承上，若網站本身不按推出時間排序，以流水號編號實在沒多大意義。

---

按照資料夾的建立日期排列也就相當於按照章節列表排列，因為章節資料夾只有在下載圖片時才會被建立。既然下載時是按照章節列表下載，資料夾的建立時間也就按章節列表排序。
