### ISSUE TITLE
ikanman下載的一個問題

### ISSUE THREAD

**Issue by wby238** [eight04/ComicCrawler#44]
在下載《[七公主](http://www.ikanman.com/comic/9424/)》時，遇到一個空白圖片（第46話08頁），開啟對應的[網址](http://www.ikanman.com/comic/9424/94839.html#p=8)，線路是自動時無法載入圖片（信息如下），但線路是電信或聯通是載入正常。

> 图片载入失败，请 " 按F5键刷新页面 " 或 "切换服务器线路" ，如果依然不行，请 " 进行报错，管理员会尽快解决 " :(

**Comment by eight04** [comment]
2017/4/15 00:17 正常
