### ISSUE TITLE
建立資料夾時出問題了

### ISSUE THREAD

**Issue by wby238** [eight04/ComicCrawler#46]
網址：http://www.ikanman.com/comic/12912/

出錯日誌：
```python
Downloading 第94回 忠归本心... page 1: http://idx0.hamreus.com:8080/ps1/j/jyny/
第94回/1_6976.jpg

Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\comiccrawler\core\__init__.p
y", line 434, in save_image
    content_write(self.savepath.full_fn(self.get_filename(), self.image_ext), se
lf.image_bin)
  File "c:\program files\python35\lib\site-packages\comiccrawler\io.py", line 49
, in content_write
    with io.open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Comics\\ikanman\\家
有女友\\第94回 忠归本心...\\001.jpg@2017-04-16_232720'
停止下載
Session saved
```

實際建立的資料夾名為“第94回 忠归本心”

**Comment by eight04** [comment]
？！看來 python 不能建立含有 trailing dots 的資料夾……用 Node 時沒遇到這問題。

http://bugs.python.org/issue22744
http://stackoverflow.com/questions/11681207/how-to-create-a-filename-with-a-trailing-period-in-windows

我想有兩種做法︰

1. 修正資料寫入/讀取的程式碼，讓名稱包含 trailing dots 時也能運作。但即使 Comic Crawler 可以處理，也不表示其它程式（如檔案總管、看圖軟體）能正確處理 trailing dots。
2. 直接修改檔案名稱，若結尾包括非法字元「.」就自動加個底線之類的。

感覺 (2) 比較容易，相容性也比較好一點，不過 `第94回 忠归本心...` 會變成 `第94回 忠归本心..._`。

**Comment by wby238** [comment]
不對啊，有類似的一話是建立成功的啊……

> 第89回 作为父亲…

**Comment by eight04** [comment]
第 89 回後面接的是全型字元，刪節號；第 94 回後面接的是半型字元，句號。兩者是不一樣的。

**Comment by eight04** [comment]
Fixed in 2017.4.18.
