### ISSUE TITLE
代理支持

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#5]
dm5.com的某些漫画在大陆使用时，会因内容不和谐(过于血腥等等)而无法查看/下载。
使用代理翻出大陆后就可以查看/下载了。
请提供一个http/socks5的代理选项以解决这个问题。
多谢！

**Comment by eight04** [comment]
感覺是個實用的功能。有試過類似 Proxifier 的軟體嗎？

**Comment by petronny** [comment]
我不是windows用户。。

我在linux下可以通过开全局代理让ComicCrawler正常访问被和谐的内容并下载。
不过这样其他应用也会被迫经过代理，不是很方便。

**Comment by eight04** [comment]
設成參數可行，但我會更傾向於增加一個 proxy 設定放在 setting.ini 內，如此一來可以為了個別模組設定︰
```
[動漫屋]
proxy = socks5://127.0.0.1:1080
```

另外我在 Google「linux proxifier」時有看到些連結不知道是否有用︰
* [A software like Proxifier for linux?](http://superuser.com/questions/424045/a-software-like-proxifier-for-linux)
* [Is there any utility like `Proxifier` for Ubuntu?](http://askubuntu.com/questions/117967/is-there-any-utility-like-proxifier-for-ubuntu)

**Comment by starobots** [comment]
多谢eight04的更新，有了gui之后使用方便多了。
另外，建议在使用说明里面写一下“使用需要登录的网站要在设定（setting.ini）里面填一下cookies”。这样就不用再找怎么载入cookies。
感谢。

**Comment by eight04** [comment]
更新了 readme，增加關於設定檔的說明。

下次如果有和原主題無關的 issue，可以開一個新的避免文不對題。

**Comment by petronny** [comment]
目前使用的下述办法：
* 如果是http代理

那么通过
```
http_proxy=host:port comiccrawler gui
```
运行就可以了

* 如果是socks代理

先使用polipo将socks代理转换成http代理，即`/etc/polipo/config`设置为
```
socksParentProxy = "host:port"
socksProxyType = socks5
```

然后再使用上述办法就可以了

> 其实我之前是忘了是哪个软件可以把socks转成http代理了。。
