### ISSUE TITLE
动漫之家的漫画下不了？

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#51]
http://manhua.dmzj.com/snsfdpj
之前也是，选择分卷之后，卡在downloading ep就不动了，然后就跳到下一卷，downloading ep，始终不开始下载。

**Comment by starobots** [comment]
http://www.dm5.com/manhua-feichangjiating/
动漫屋的也是，在不同分卷之间就downloading ep。

**Comment by eight04** [comment]
2017.4.22 沒問題。無法下載時的錯誤訊息是？

**Comment by starobots** [comment]
就写的是downloading ep 然后就没法开始下载。
不同分卷之间就循环downloading ep，然后就开始下一卷downloading ep。
奇怪，，换个电脑就好用。

**Comment by eight04** [comment]
可以的話試著把 cmd 視窗擷圖。
不同電腦之間有作業系統或 python 版本差異嗎？

**Comment by starobots** [comment]
我用那个升级命令升级了一下，看看能不能修复。
我实在不懂编程，还是麻烦您。
attribute error是属性错误？
还有一个是什么文件找不到。。。
现在错误截图是：
![image](https://cloud.githubusercontent.com/assets/10796457/25344947/3dbe2554-2946-11e7-93cf-a0ab8db5b21a.png)
![image](https://cloud.githubusercontent.com/assets/10796457/25344988/54c72b88-2946-11e7-970e-9791c2e3cf97.png)

**Comment by starobots** [comment]
谢谢！

**Comment by eight04** [comment]
程式找不到 Node.js，請確認是否有安裝最新版本的 Node.js
https://nodejs.org/

**Comment by starobots** [comment]
谢谢，解决了这个问题。
话说能不能增加一个批量下载的框框。
把链接直接一起贴进去让他慢慢分析。

**Comment by eight04** [comment]
在 2017.4.18 之後的版本就有批次加入的功能了
