### ISSUE TITLE
dm5 - 上中下分割類型的作品的問題

### ISSUE THREAD

**Issue by zfnuooq5** [eight04/ComicCrawler#54]
http://www.dm5.com/manhua-ribenyaoguaidaquan/
例如這個
它看起來有三個第1卷，但點進去是 [第1卷：上]、[第1卷：中]、[第1卷：下] 三個部份。
ComicCrawler目前選全部下載只能抓到 [第1卷：上]和[第2卷：上]，其他部份因為名字一樣的關係抓不到。

**Comment by eight04** [comment]
於 2017.4.26 修正，現在的章節名是從表格內取得。
