### ISSUE TITLE
小建议：最小化之后gui隐藏在任务栏托盘里。

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#55]
现在用gui模式下，会显示一个命令行窗口和软件gui界面。
话说能不能变成最小化之后隐藏到任务栏托盘里哈。
谢谢！

**Comment by eight04** [comment]
tkinter 沒有內建的 tray icon，我看了 pypi 有類似的 package︰
https://pypi.python.org/pypi/pystray/
https://pypi.python.org/pypi/AllTray/

不過我認為這功能不值得再引用更多的 library 來實作，我比較傾向用如 [RBTray](http://rbtray.sourceforge.net/) 等的工具。

**Comment by starobots** [comment]
好的谢谢。

**Comment by starobots** [comment]
不好意思，问一下，我的pool.json文件损坏，能不能自己恢复。。。
应该是保存session的时候意外断电了，只有pool文件夹里面的内容完好，pool.json用写字板打开里面是乱码，应该是文字编码问题。我应该怎么恢复？

**Comment by starobots** [comment]
eight，您好！
再次谢谢您的工作！
我就写这里了。
看漫画加了一个域名。
http://www.manhuagui.com/
在mod里面找半天ikanman，结果原来是叫seemh哈。
我这自己改好了，下次更新的时候麻烦您加上。
谢谢！

**Comment by starobots** [comment]
不好意思，加进去图书馆里面的ikanman的域名的漫画也都没法检查更新。
好像是library.json里面读取pool文件夹的内容？
pool文件夹里面要改的东西就太多了。。。。

**Comment by eight04** [comment]
1. 以後遇到新問題，請開一個 New Issue
2. 解決問題後，請用回覆功能。不要用編輯功能把原問題刪除。
