### ISSUE TITLE
煩請協助更新www.99comic.com

### ISSUE THREAD

**Issue by pobynb** [eight04/ComicCrawler#63]
該網站網址已更新為www.999comic.com，有試著新增一個999.py
但還是會出現錯誤
https://imgur.com/xEThQ
再麻煩您了，謝謝

**Comment by eight04** [comment]
之前有人回報 99 變成 http://99.hhxxee.com/ ，而 http://www.hhxxee.com/ 則是虎虎漫畫。其它的分身還有︰

http://dmeden.net/
http://www.cococomic.com/
http://mh.99770.cc/

資源都微妙的差不多。

我會測試把 http://99.hhxxee.com/ 網域加入名單內是否能繼續運作。但若是不行，目前沒有再重新支援 99 的打算，除非有資源是別站找不到的。

**Comment by pobynb** [comment]
剛看了一下，您貼的幾個網站真的資源都差不多 XD
感謝您，待連假結束再測試看看，謝謝
原本是因為只有www.999comic.com才有火影1-72集單行本
其餘大多是1回1回的連載版本

**Comment by eight04** [comment]
於 2017.5.29 修正。請轉用 99.hhxxee.com

**Comment by pobynb** [comment]
謝謝您，連假還幫忙修改，辛苦了
