### ISSUE TITLE
Sankaku無法更新

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#66]
檢查圖書館更新時遇到問題
當檢查到Sankaku的網址時，就會跳出"You didn't login"
但是瀏覽器上和設定檔裡填入的cookie，確認過是一樣的
https://drive.google.com/file/d/0B3tdsTxJnPOBV2RBLVp5MjV6TGM/view
https://drive.google.com/file/d/0B3tdsTxJnPOBdF9YLVRLUEFZbjQ/view
想請教下該怎麼解決這個狀況
謝謝~

**Comment by eight04** [comment]
於 2017.8.13 修正。Cookie 中多了一項 login 需要輸入。
