### ISSUE TITLE
仍然不支持手动指定Proxy？

### ISSUE THREAD

**Issue by tzw0745** [eight04/ComicCrawler#67]
大陆IP地址访问http://comic.sfacg.com或出现403错误。本地http代理为127.0.0.1:1080。
在 setting.ini 中的 [DEFAULT] 下添加 proxy = 127.0.0.1:1080 参数，不使用代理；
在 setting.ini 中的 [DEFAULT] 下添加 http_proxy = 127.0.0.1:1080 参数，不使用代理；
在 setting.ini 中的 [DEFAULT] 下添加 proxy = http://127.0.0.1:1080 参数，不使用代理；
在 setting.ini 中的 [DEFAULT] 下添加 proxy = https://127.0.0.1:1080 参数，不使用代理。
在 setting.ini 中的 [DEFAULT] 下添加 http_proxy = http://127.0.0.1:1080 参数，不使用代理；
在 setting.ini 中的 [DEFAULT] 下添加 http_proxy = https://127.0.0.1:1080 参数，不使用代理。

PS：我使用的代理软是shadow socks，http://comic.sfacg.com 已加入到其PAC规则中，浏览器访问时不需要设置成全局代理模式；而使用ComicCrawler时必须要将ss设置成全局代理才能访问。

**Comment by eight04** [comment]
目前 Comic Crawler 無法使用 proxy 連線。之前曾經有討論過是否要新增 proxy 功能，見 #5 ，但後來又被 closed 了。

**Comment by tzw0745** [comment]
```
[動漫屋]
proxy = socks5://127.0.0.1:1080
```
太可惜了，这是一个很好的想法

**Comment by eight04** [comment]
http://docs.python-requests.org/en/master/user/advanced/#proxies
Requests 好像可以從環境變數設定 proxy。試試︰
```bat
SET HTTP_PROXY=http://127.0.0.1:1080
SET HTTPS_PROXY=http://127.0.0.1:1080
comiccrawler gui
```

**Comment by tzw0745** [comment]
设置系统变量会影响其它使用requests的python程序吧

**Comment by eight04** [comment]
使用 `SET` 指令並不會建立系統級的環境變數，只會影響同個 cmd 內執行的程式。若要建立系統/使用者級的環境變數，可以用 `SETX` 指令。

**Comment by tzw0745** [comment]
受教了。将上述命令写入BAT脚本时即可在本次执行ComicCrawler时使用代理。
先前我用的方法是修改'comiccrawler.core.grabber.py'中的'do_request'函数，不过这样的话就相当于ComicCrawler全局使用代理了。

当然，我认为最合适的做法仍然是对指定站点设置代理。

**Comment by eight04** [comment]
會改的話，要不要送個 PR？我看了下，大概要在這裡送 proxy 設定給 grabber︰
https://github.com/eight04/ComicCrawler/blob/9f0ebb2f54c5eec26db49fb17d67f9fd846fcfc2/comiccrawler/core/__init__.py#L241-L257
類似
```python
grabsomething(..., proxy=self.mod.config.get("proxy"))
```

**Comment by tzw0745** [comment]
修改：ComicCrawler/comiccrawler/core/__init__.py
```python
	def html(self, url, **kwargs):
		proxy = self.mod.config.get("proxy")
		proxies = {'http': proxy, 'https': proxy} if proxy else None
		return grabhtml(
			...,
			proxies=proxies,
			**kwargs
		)
	
	def img(self, url, **kwargs):
		proxy = self.mod.config.get("proxy")
		proxies = {'http': proxy, 'https': proxy} if proxy else None
		return grabimg(
			...,
			proxies=proxies,
			**kwargs
		)
```

修改：ComicCrawler/comiccrawler/core/grabber.py
```python
def grabber(url, header=None, *, referer=None, cookie=None, raise_429=True, params=None, done=None, proxies=None):
	...
	
	r = await_(do_request, s, url, params, proxies, raise_429)
	
	...
		
def do_request(s, url, params, proxies, raise_429):
	while True:
		r = s.get(url, timeout=20, params=params, proxies=proxies)
		...
	...
```

修改setting.ini即可
```
[SF]
proxy = 127.0.0.1:1080
```

PS：在我这用ss开启代理测试通过。不过这里没有将http和https分开，也没有考虑socket5代理，不知道能不能通用。
