### ISSUE TITLE
pixiv的命名規則

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#72]
新加入的pixiv網址，任務的命名規則變得跟以往不一樣
https://drive.google.com/file/d/0B3tdsTxJnPOBcFh3aVpCbE95NW8/view
請問可以改回原本的命名規則嗎 (ex: 360177 - 鮫妻丈二)
謝謝~

**Comment by eight04** [comment]
於 2017.8.26 修正。

Pixiv 在改版後抓不到使用者名稱，而在抓不到使用者名稱的狀況下會自動使用網頁標題，就變這樣了。
