### ISSUE TITLE
Sankaku下載出問題

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#75]
雖然cmd裡看不出異常，不過實際下載下來的圖片全部不正確
https://drive.google.com/file/d/0B3tdsTxJnPOBUnY3YzAtSlFicFU/view
https://drive.google.com/file/d/0B3tdsTxJnPOBSVZ4bnJtUWduNnM/view
似乎都被導向到下面這個網址
https://chan.sankakucomplex.com/expired.png

**Comment by eight04** [comment]
於 2017.9.5 修正。那些 `&amp;` 沒有被替換成 `&`。
