### ISSUE TITLE
關於Tumblr圖片擷取網址

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#82]
http://raburine.tumblr.com/post/165056526134/based-on-this-commission-info-facebook
以這張圖為例
直接點選圖片，出現的圖片網址是：
http://78.media.tumblr.com/4e66c299255bf2096d332d6a1a27653b/tumblr_ovvn8cNPn11r2hxu1o1_1280.png
把78.media改成data、1280改成raw：
http://data.tumblr.com/4e66c299255bf2096d332d6a1a27653b/tumblr_ovvn8cNPn11r2hxu1o1_raw.png
才是原始圖檔網址

希望能修改擷取的網址，以便從Tumblr下載原圖，謝謝

**Comment by eight04** [comment]
於 2017.12.4 修正。
