### ISSUE TITLE
同名相簿導致下載時誤判

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#83]
例如

https://exhentai.org/g/1150022/cce30da3bd/
https://exhentai.org/g/1149592/409ae59095/

雖然英文名稱不同
但標題都是 데스티니 차일드 움짤

導致下載時誤判已經下載過
只下載了 兩個相簿之間 差異的頁次

對於下載時的相簿名稱
也許該做分類
例如 A站 / B相簿+相簿ID 之類的感覺

**Comment by eight04** [comment]
題外話，其實新加入的相簿類網站都有使用 ID 和站名作為任務名稱，而 EXH 是非常早期的模組，甚至可以 說 Comic Crawler 的前身就是某個 EXH 下載工具，所以就很簡單的使用了標題作為任務名稱。

**Comment by eight04** [comment]
於 2017.12.4 修正。
