### ISSUE TITLE
Tumblr沒有下載原始大圖

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#86]
https://drive.google.com/file/d/1Mji_dTqvgT8S_UQsnf-4ctI15MobJXK3/view

調整 full_size 和 insecure_http 選項也沒有幫助
一樣是下載_1280的縮圖 而不是_raw的原圖

**Comment by eight04** [comment]
我把 http 和 https 寫反了，已於 2017.12.14 修復。

補充︰

* `full_size` 控制是否要下載大圖（`true` = 是/`false` = 否）
* `insecure_http` 控制是否要把 HTTPS 轉成 HTTP

兩項都要調成 true 才能成功下載 https://shonep.tumblr.com/ 的大圖。
