### ISSUE TITLE
Tumblr還是沒有下載原始大圖

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#87]
已將 comiccrawler 更新成最新版
setting.ini 裡 full_size 和 insecure_http 也都調成 true 了
下載的還是_1280的縮圖
以下附上 cmd 和 setting.ini 截圖
https://drive.google.com/file/d/1ELe7eyUMhZsy2bPQWTyib0leMYiQBUol/view
https://drive.google.com/file/d/1aqbU2BPmUg8vT1RaUGljhDnrm1L-HNqw/view

**Comment by eight04** [comment]
你的設定是自行加上去的嗎？模組名稱應該是 `tumblr`（小寫 `t`）而非 `Tumblr`。

以後可以更新完後︰

1. 啟動 Comic Crawler
2. 關閉 Comic Crawler
3. 如此一來新的設定就會被寫入設定檔。不用自行添加，只要修改值就就可以了。

**Comment by chenhan200** [comment]
確實我是手動加入的
以前一直不知道要怎麼讓設定檔自動更新
感細告知
