### ISSUE TITLE
Pixiv動圖下載附檔名變成 .ugoira

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#88]
雖然一樣可以用WinRAR之類的軟體開啟
還是希望能改回原本的.zip
謝謝

**Comment by eight04** [comment]
用 .ugoira 的好處是 HoneyView 可以直接讀取/顯示動畫。想改回原先的 .zip 原因是？

**Comment by chenhan200** [comment]
那就保留這個變更吧
抱歉不知道還有這麼方便的用法(

**Comment by eight04** [comment]
我也是不久前才知道 #85
