### ISSUE TITLE
幾個小提議

### ISSUE THREAD

**Issue by chihan3ting** [eight04/ComicCrawler#89]
您好！用了comiccrawler抓了那麼多圖，飆了那麼多車。十分感謝作者編寫的軟體帶來的便利！故有幾個問題，或者說是提議請指教。

1.有關於文件命名！有時候在同一頁網頁抓圖時，up主有時會把兩個相同文件名的圖片放在同一頁，例如001.png，002.png【黑】，003.png，002.png【白】，004.png，005.png......但其中命名為002的兩個文件並不是同一個文件，由於在同一目錄下，軟體抓圖下來時，會用後面的img_002.png【白】覆蓋掉前面已經抓下的img_002.png【黑】。請問能不能實現在同一目錄下，當抓到同一文件名但卻是不同文件的時候，在後抓的圖命名上加上副標題，即002(1).png。這個類似PC同一目錄下，重複文件就在原文件名後添加副標題的重命名。請問可不可以實現？

2.有關於圖源的身份驗證。有些圖源網站是有地區IP限制的，紳士往往需要掛代理才能抓圖。由於網絡環境較差[代理有時當機重啟]，以及原圖源數量過於多，單文件過大[高清大圖通常上數MB]，會造成抓圖不成功。例如抓個4MB的原圖，突然網絡延遲或斷聯了後重聯，軟體就只抓2.33MB的原圖就跳過抓下一個圖了，造成原本4MB的原圖只有2.33MB的壞檔。2.33MB圖片雖然可以打開，但只顯示一半，下半部是灰的一片。我覺得可以參考hash驗證這種方法，例如從網盤下載某分享文件，up主貼出hash值，在紳士下載完這個文件後，校驗hash值，對比up主貼出的hash，確保文件完整性。類比comiccrawler，可以加入這個機制，抓完一張圖，本地與網源同時對比hash，確保圖源完整性，是就跳到下一張圖，否就自動刪除壞檔重新下載。這樣不用在抓完一堆CG後，還要一張張視察。作者您覺得如何？

3.翻看了G託管的許多討論，其中有說到是否需要在軟體中添加代理，個人覺得沒有必要。在使用代理軟體時，設置全局代理，再啟用comiccrawler時就可以規避IP地區限制了，前提是代理的IP在允許的範圍內。推薦影梭，但需要VPS，具體使用及說明就不多說了，作者可以多了解。

說了那麼多廢話，不好意思呢！謝謝閱讀！望comiccralwer功能更強大，使用更方便！

另，不知為何博客無法留言，只能發到這。謝謝！

**Comment by eight04** [comment]
> 1.

* 網址是？
* `originalfilename` 的選項是？

ComicCrawler 理應不會做 *任何* 檔案覆蓋的動作。若有檔案已存在於資料夾，ComicCrawler 應該會跳過才是。

> 2.

遇到網路錯誤時，ComicCrawler 應該是不會把檔案寫進硬碟裡的。會儲存毀損文件，我想有幾種可能︰

1. 在無網路錯誤的情況下，伺服器自己回傳了毀損的圖片
2. 在無網路錯誤的情況下，VPN 回傳了毀損的圖片

不過我對網路不熟，也不確定問題在哪。

> 校驗hash值

可行，但老實說我還沒看過哪個漫畫網站會提供圖片的 hash 值給使用者。

**Comment by chihan3ting** [comment]
1.
original = true
originalfilename = true
例如 https://exhentai.org/g/323260/f04af39a6a/
     https://exhentai.org/g/323260/f04af39a6a/?p=12

這個是舊遊戲CG，最後一頁的部分圖與首頁的部分圖命名重複了，我重新抓了一遍，確定comiccralwer不會覆蓋前面相同命名文件，而是跳過了，但並沒有全抓完，這是個問題。是我的失誤，不好意思！

2.關於校驗hash，這只是個籠統的說法，只是個關於文件的唯一性與正確性的問題。舉個例子，我用網頁瀏覽器從伺服器上抓個分享的視頻文件A。從download開始，假如在download過程中，伺服器被攻擊重啟或自動重啟時，會返回錯誤給瀏覽器，而瀏覽器這邊就會顯示未知錯誤，需要手動重新從零開始download，而瀏覽器與伺服器重新建立對話，直到所抓文件完整download下來。數據校驗通過傳輸對話完成的，即每個數據塊正確性瀏覽器都會詢問伺服器，碰到錯誤數據就會直接丟棄【即刪除】，再向伺服器請求相同數據。如此操作才能保證瀏覽器抓到的文件A就是你伺服器上的文件A，而不是將錯就錯的文件a。而comiccrawler在抓圖時，在碰到vpn或sock代理，更甚至圖源伺服器時，網絡閃了閃腰，它就會將抓了一半斷聯的數據變成文件a當成文件A保存下來，下一步就抓文件B了。comiccrawler提供了抓圖的便利卻沒有確保數據的完整。如何讓comiccrawler抓到我要的文件A，而不是將環境出錯造成數據錯誤，就錯誤數據當成文件A丟還給我時，這是個命題。

另，有些地區的互聯網是經過過濾與屏蔽的，其中明文數據是很容易被查看和進行添加操作的，更別說對加密類的[ssl]進行屏蔽和干擾了。其中的複雜性，自由國度的作者很難想像。

以上是個人作為使用者的看法與理解，而非專業人士，其中錯誤與不當之處望請指正與諒解。謝謝！

**Comment by eight04** [comment]
> 1.

已確認有重覆檔名，**並且 ComicCrawler 的確會在這種情況下，將第 11 頁以第 246 頁覆蓋**︰

* https://exhentai.org/s/db1e11a4b4/323260-11
* https://exhentai.org/s/dbe63a5717/323260-246

看來若要確保檔名不重覆，還是得在檔名上加上頁數，但如此一來就失去了使用原始檔名的意義。

或許我們可以限制同個 Episode 內的檔名不得重覆，但若檔名是動態抓下來的這方法就不管用了︰
https://github.com/eight04/ComicCrawler/blob/2ae11cf2b96a4be10a3c71f34708d501d5d10372/comiccrawler/core/__init__.py#L404-L406

順帶一提，重覆的檔名會被跳過這件事情其實 [在實作前有討論過](http://eight04.blogspot.tw/2014/03/comic-crawler.html?showComment=1482133605239#c7712450057738888118)。

大概可行的解法︰

1. 移除動態獲取檔名
2. 限制同個 Episode 內不得包含同名檔案，或是在設定檔中增加「遇到同名檔案時自動重命名」的選項。

> 2.

網址是？不過如果這個現象只限於使用 VPN 時才有，我也無法保證我的電腦會測試出一樣的結果。

如果你可以協助測試的話，把設定中的 `errorlog` 設成 `true`，在遇到這種情況時，把 `grabber.log` 和毀損的文件傳給我。**注意，gabber.log 內有記錄使用者設定的 Cookie，傳給我之前請先將包含使用者資料的 Cookie 打碼（替換為 * 字元）**。

**Comment by chihan3ting** [comment]
部分測試已發郵件，注意查收！謝謝！

**Comment by eight04** [comment]
沒有收到。可以直接打包成 zip 並 [傳上來](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) 嗎？

**Comment by eight04** [comment]
另外，毀損很常見嗎？根據你回應的時間，幾個小時內就又發生了檔案毀損的現象？

**Comment by chihan3ting** [comment]
壞檔樣本發到你的博客的G郵箱了，注意查收。

2018-01-20 18:17 GMT+08:00 eight <notifications@github.com>:

**Comment by eight04** [comment]
感謝回報，移至 #90, #91.
