### ISSUE TITLE
問題回報

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#9]
剛更新到4.4的最新版，然後想加一個comicbus的漫畫進去
出現錯誤訊息，後來又試了動漫之家和dm5也都一樣，以下是錯誤圖片
https://i.imgur.com/jELd4cC.png
https://i.imgur.com/cHNhPu6.png

**Comment by eight04** [comment]
已確認，等等修

**Comment by eight04** [comment]
已於 2016.4.8 修正

**Comment by kesdoputr** [comment]
感謝神速修正m(_ _)m
